private ["_allweps","_spitweps","_playertype","_wep"];

waituntil {sleep 1; Hz_initdone};

_playertype = toupper Hz_playertype;

//weapons for public players. everyone gets these
Hz_client_allowed_weps = [
"AK_47_M","ACE_AKM","ACE_AKMS","AK_47_S","ACE_AKMS_SD","AK_74","AKS_74","AKS_74_KOBRA","AKS_74_U","AKS_74_UN_KOBRA","ACE_AKS74_UN","FN_FAL","ACE_G3A3","ACE_HK416_D10","ACE_HK416_D14","LEEENFIELD",
"M14_EP1","M16A2","ACE_M16A2_SCOPE","ACE_M3A1","ACE_M4_C","ACE_M4A1_C","ACE_MP5A4","MP5A5","ACE_MP5A5","MP5SD","ACE_MP5SD","SAIGA12K","ACE_SKS","ACE_UMP45","ACE_WIRECUTTER","ACE_STRETCHER","ACE_PARACHUTEROUNDPACK",
"ACE_JERRYCAN_DUMMY_15","BINOCULAR","NVGOGGLES","ACE_VTAC_RUSH72_OD","ACE_VTAC_RUSH72","ACE_VTAC_RUSH72_ACU",
"ACRE_PRC343","ACE_GLASSESSUNGLASSES","ACE_GLASSESBALAKLAVA","ACE_GLASSESBALAKLAVAGRAY","ACE_GLASSESBALAKLAVAOLIVE","ITEMCOMPASS","ACE_KEYCUFFS","ACE_EARPLUGS","ACE_GLASSESGASMASK_RU","ACE_GLASSESGASMASK_US","ITEMGPS",
"ITEMMAP","ACE_MAP","ACE_GLASSESLHD_GLASSES","ACE_GLASSESBLACKSUN","ACE_GLASSESBLUESUN","ACE_GLASSESREDSUN","ACE_GLASSESGREENSUN","ACE_GLASSESTACTICAL","ITEMWATCH","M9","MAKAROV","ACE_APS","MAKAROVSD","ACE_APSB","UZI_EP1",
"UZI_SD_EP1","ACE_MUGLITE","REVOLVER_EP1","SA61_EP1","ACE_TT",
        
//weird stuff we need to add
"ACE_LASERDESIGNATOR_HIDDEN","ACE_M136_USED","ACE_M72A2_USED","ACE_RPG18_USED","EVDOGTAGS"
        
];

if (_playertype == "WHITELIST") then {

    Hz_client_allowed_weps = Hz_client_allowed_weps +
    [
    "ACE_G36K_IRON","ACE_AK103","ACE_AK103_1P29","ACE_AK103_KOBRA","ACE_AK104","ACE_AK104_1P29","ACE_AK104_KOBRA","ACE_AK105","ACE_AK105_1P29","ACE_AK105_KOBRA","M1014","ACE_SPAS12",
    "AK_107_KOBRA","ACE_AK74M","ACE_AK74M_FL","ACE_AK74M_FL_F","ACE_AK74M_1P29","ACE_AK74M_1P78","ACE_AK74M_1P78_FL","ACE_AK74M_1P78_FL_F","ACE_AK74M_KOBRA","ACE_AK74M_KOBRA_FL","ACE_AK74M_KOBRA_FL_F",
    "ACE_AK74M_SD_F","ACE_AK74M_SD","ACE_AK74M_SD_1P78","ACE_AK74M_SD_1P78_F","ACE_AK74M_SD_KOBRA","ACE_AK74M_SD_KOBRA_F","AKS_74_PSO","ACE_AKS74P","ACE_AKS74P_1P29","ACE_AKS74P_KOBRA","BIZON","BIZON_SILENCED",
    "G36C","ACE_G3A3_RSAS","ACE_G3A3_RSAS_F","ACE_HK416_D10_SD","ACE_HK416_D14_SD","ACE_KAC_PDW","BAF_L85A2_RIS_SUSAT",
    "ACE_M1014_EOTECH","ACE_M14_ACOG","ACE_M16A4_IRON","ACE_M4","ACE_M4_AIM","ACE_M4_AIM_F","ACE_M4_F","ACE_M4_EOTECH","ACE_M4_EOTECH_F","M4A1","M4A1_AIM","ACE_M4A1_AIM_F","ACE_M4A1_AIM_SD",
    "ACE_M4A1_AIM_SD_F","ACE_M4A1_F","ACE_M4A1_EOTECH","ACE_M4A1_EOTECH_F","SCAR_L_CQC","ACE_MP7","ACE_UMP45_AIM","ACE_UMP45_SD","ACRE_PRC119","ACE_MAP_TOOLS","GLOCK17_EP1","COLT1911","ACE_L9A1","M9SD",
    "ACE_MINEDETECTOR_US","ACE_YARDAGE450",
        
    "ACE_AEK_971","ACE_AEK_971_TGP_CLN","ACE_AEK_971_SHAHIN","ACE_AEK_971_1PN100","ACE_AEK_971_1P78","ACE_AEK_971_GP_1P63","ACE_AEK_971_1P63","ACE_AEK_971_GP","ACE_AEK_973S",
    "ACE_AEK_973S_SHAHIN","ACE_AEK_973S_TGP_CLN","ACE_AEK_973S_1PN100","ACE_AEK_973S_1P78","ACE_AEK_973S_GP_1P63","ACE_AEK_973S_1P63","ACE_AEK_973S_GP",
        
    "ACE_AK103_PSO","ACE_AK104_PSO","ACE_AK105_PSO","AK_107_PSO","ACE_AK74M_TWS","ACE_AK74M_TWS_FL_F","ACE_AK74M_TWS_FL","ACE_AK74M_NSPU","ACE_AK74M_NSPU_FL","ACE_AK74M_NSPU_FL_F","ACE_AK74M_PSO",
    "ACE_AK74M_PSO_FL","ACE_AK74M_PSO_FL_F","ACE_AK74M_SD_TWS","ACE_AK74M_SD_TWS_F","ACE_AK74M_SD_NSPU","ACE_AK74M_SD_NSPU_F","ACE_AK74M_SD_PSO","ACE_AK74M_SD_PSO_F","AKS_GOLD","AKS_74_GOSHAWK",
    "AKS_74_KOBRA","AKS_74_NSPU","AKS_74_PSO","ACE_AKS74P_PSO","ACE_VAL_KOBRA","ACE_VAL_PSO","ACE_VAL","FN_FAL_ANPVS4","G36A","G36K","G36A_CAMO","ACE_G36A2","ACE_G36A2_D_F","ACE_G36A2_D","ACE_G36A2_F",
    "G36C_CAMO","G36_C_SD_CAMO","G36_C_SD_EOTECH","G36K_CAMO","ACE_G36K_IRON_D","ACE_G36K_EOTECH","ACE_G36K_EOTECH_D","ACE_GR1","ACE_GR1SP","ACE_GR1SD","ACE_GR1SDSP","ACE_OC14","ACE_OC14SP","ACE_OC14SD","ACE_OC14SDSP",
    "ACE_HK416_D10_COMPM3","ACE_HK416_D10_COMPM3_SD","ACE_HK416_D10_HOLO","ACE_HK416_D10_AIM","ACE_HK416_D14_ACOG_PVS14","ACE_HK416_D14_COMPM3","ACE_HK416_D14_TWS","ACE_HK417_MICRO","ACE_HK417_EOTECH_4X",
    "ACE_HK417_SHORTDOT","BAF_L85A2_RIS_ACOG","BAF_L85A2_RIS_CWS","BAF_L85A2_RIS_HOLO","M16A4","ACE_M16A4_EOT","M16A4_ACG","ACE_M4_ACOG_PVS14","ACE_M4_ACOG_PVS14_F","ACE_M4_ACOG","ACE_M4_ACOG_F",
    "ACE_M4A1_ACOG_PVS14","ACE_M4A1_ACOG_PVS14_F","ACE_M4A1_EOT_SD","ACE_M4A1_EOT_SD_F","ACE_SOC_M4A1_EOTECH_4X","ACE_SOC_M4A1_EOTECH_4X_F","ACE_SOC_M4A1_EOTECH","ACE_SOC_M4A1_EOTECH_F","M4A1_AIM_SD_CAMO",
    "ACE_SOC_M4A1_AIM","ACE_SOC_M4A1_AIM_SD","ACE_M4A1_ACOG","ACE_M4A1_ACOG_F","ACE_M4A1_ACOG_SD","ACE_M4A1_ACOG_SD_F","ACE_SOC_M4A1_SD_9","ACE_SOC_M4A1_SHORTDOT_F","ACE_SOC_M4A1_SHORTDOT_SD_F",
    "ACE_SOC_M4A1_SHORTDOT_SD","ACE_SOC_M4A1_SHORTDOT","ACE_SOC_M4A1_EOT_SD","ACE_SOC_M4A1_EOT_SD_F","ACE_SOC_M4A1","ACE_SOC_M4A1_TWS_F","ACE_SOC_M4A1_TWS","M4A3_CCO_EP1","M8_CARBINE","M8_COMPACT",
    "M8_COMPACT_PMC","M8_CARBINE_PMC","M8_HOLO_SD","M8_TWS","M8_TWS_SD","M4A1_AIM_CAMO","SCAR_L_CQC_CCO_SD","SCAR_L_CQC_HOLO","SCAR_L_STD_HOLO","SCAR_L_STD_MK4CQT","SCAR_H_CQC_CCO","SCAR_H_CQC_CCO_SD",
    "ACE_SCAR_H_STD_SPECT",
    "ACE_MP7_RSAS","ACE_UMP45_AIM_SD","ACE_FLAREGUN","ACE_GLOCK18","ACE_P8","REVOLVER_GOLD_EP1","ACE_P226","ACE_USP","ACE_USPSD",
    "EVO_ACR","EVO_MRAD_ACR","EVO_SD_ACR","CZ805_A1_ACR","CZ805_A2_SD_ACR","CZ805_A2_ACR",
        
    //mods
    //RH416
    "RH_HK416","RH_HK416AIM","RH_HK416ACOG","RH_HK416EOTECH","RH_HK416SD","RH_HK416SDAIM","RH_HK416SDEOTECH","RH_HK416S","RH_HK416SAIM","RH_HK416SEOTECH","RH_HK416SACOG",
    "RH_HK417","RH_HK417AIM","RH_HK417ACOG","RH_HK417EOTECH","RH_HK417SD","RH_HK417SDAIM","RH_HK417SDACOG","RH_HK417SDEOTECH","RH_HK417S","RH_HK417SAIM","RH_HK417SACOG","RH_HK417SEOTECH",
    "RH_MAS","RH_MASACOG","RH_MASAIM","RH_MASEOTECH","RH_MASB","RH_MASBACOG","RH_MASBAIM","RH_MASBEOTECH","RH_MASSD","RH_MASSDACOG","RH_MASSDAIM","RH_MASSDEOTECH","RH_MASBSD","RH_MASBSDACOG",
    "RH_MASBSDAIM","RH_MASBSDEOTECH","RH_ACR","RH_ACRACOG","RH_ACRAIM","RH_ACREOTECH","RH_ACRB","RH_ACRBACOG","RH_ACRBAIM","RH_ACRBEOTECH","RH_CTAR21","RH_CTAR21M","RH_STAR21",

    //TMT HK33
    "TMTR_HK33","TMTR_HK33_HOLO","TMTR_HK33_ZF",

    //RH SMG
    "RH_UZI","RH_UZIM","RH_UZISD","RH_UMP","RH_UMPAIM","RH_UMPEOT","RH_UMPRFX","RH_UMPSD","RH_UMPSDAIM","RH_UMPSDEOT","RH_UMPSDRFX",
    "RH_TMP","RH_TMPAIM","RH_TMPEOT","RH_TMPSD","RH_TMPSDAIM","RH_TMPSDEOT","RH_P90","RH_P90I","RH_P90AIM","RH_P90EOT","RH_P90SD","RH_P90ISD","RH_P90SDAIM","RH_P90SDEOT",
    "RH_MP7","RH_MP7P","RH_MP7AIM","RH_MP7EOT", "RH_MP5SD6","RH_MP5SD6AIM","RH_MP5SD6EOT","RH_MP5SD6RFX","RH_MP5K","RH_MP5KP","RH_MP5KPDW","RH_MP5KPDWAIM","RH_MP5KPDWEOT","RH_MP5KPDWRFX",
    "RH_MP5A5","RH_MP5A5AIM","RH_MP5A5EOT","RH_MP5A5RFX","RH_MP5A5RIS","RH_MP5A5RISAIM","RH_MP5A5RISEOT","RH_MP5A5RISRFX",
    "RH_MP5A4","RH_MP5A4AIM","RH_MP5A4EOT","RH_MP5A4RFX","RH_MAC10","RH_MAC10P","RH_KRISS","RH_KRISSAIM","RH_KRISSEOT","RH_KRISSRFX","RH_KRISSSD","RH_KRISSSDAIM","RH_KRISSSDEOT","RH_KRISSSDRFX",
    "RH_HK53","RH_HK53AIM","RH_HK53EOT","RH_HK53RFX",

    //RH M4
    "RH_M16A4","RH_M16A4ACOG","RH_M16A4AIM","RH_M16A4EOTECH","RH_M16A3","RH_M16A3AIM","RH_M16A3S","RH_M16A3C","RH_M16A3CS","RH_M16A2","RH_M16A2AIM","RH_M16A2S","RH_M16A1","RH_M16A1S",
    "RH_M4A1","RH_M4A1R","RH_M4A1AIM","RH_M4A1EOTECH","RH_M4A1ACOG","RH_M4SD","RH_M4SDAIM","RH_M4SDACOG","RH_M4SDEOTECH","RH_M4AIM_WDL","RH_M4SDAIM_WDL","RH_M4","RH_M4R",
    "RH_M4AIM","RH_M4EOTECH","RH_M4ACOG","RH_M4SBR","RH_M4SBRAIM","RH_M4SBREOTECH","RH_M4SBRACOG","RH_M4M","RH_M4MAIM","RH_M4MEOTECH","RH_M4MACOG","RH_AR10","RH_AR10S",

    //RH M14
    "RH_M14","RH_M14ACOG","RH_M14AIM","RH_M14EOT","RH_SC2","RH_SC2ACOG","RH_SC2AIM","RH_SC2EOT","RH_SC2SHD","RH_M1S","RH_M1SACOG","RH_M1SAIM","RH_M1SEOT","RH_M1SSHD",
    "RH_M1ST","RH_M1STACOG","RH_M1STAIM","RH_M1STEOT","RH_M1STSHD",

    //Hz M16A3 RAS
    "HZ_M16A3RAS","HZ_M16A3RAS_CCO","HZ_M16A3RAS_EOT","HZ_M16A3RAS_RCO",
         
    "C1987_G3","GMS_K98","HKG3A6","HKG3A4","G36C_AIM_JEY","G36C_AIM_SD_JEY","G36C_AIM3X_JEY","G36C_AIM3X_SD_JEY","G36C_D_AIM_JEY",
		"G36C_D_AIM_SD_JEY","G36C_D_AIM3X_JEY","G36C_D_AIM3X_SD_JEY"
        
    ];
        
} else {
    
    if (_playertype == "SUPERVISOR") then {
     
        //same as whitelist except for AA-12
        Hz_client_allowed_weps = Hz_client_allowed_weps +
        [
        "AA12_PMC","GMS_K98_KNIFE",
        
        "ACE_G36K_IRON","ACE_AK103","ACE_AK103_1P29","ACE_AK103_KOBRA","ACE_AK104","ACE_AK104_1P29","ACE_AK104_KOBRA","ACE_AK105","ACE_AK105_1P29","ACE_AK105_KOBRA","M1014","ACE_SPAS12",
        "AK_107_KOBRA","ACE_AK74M","ACE_AK74M_FL","ACE_AK74M_FL_F","ACE_AK74M_1P29","ACE_AK74M_1P78","ACE_AK74M_1P78_FL","ACE_AK74M_1P78_FL_F","ACE_AK74M_KOBRA","ACE_AK74M_KOBRA_FL","ACE_AK74M_KOBRA_FL_F",
        "ACE_AK74M_SD_F","ACE_AK74M_SD","ACE_AK74M_SD_1P78","ACE_AK74M_SD_1P78_F","ACE_AK74M_SD_KOBRA","ACE_AK74M_SD_KOBRA_F","AKS_74_PSO","ACE_AKS74P","ACE_AKS74P_1P29","ACE_AKS74P_KOBRA","BIZON","BIZON_SILENCED",
        "G36C","ACE_G3A3_RSAS","ACE_G3A3_RSAS_F","ACE_HK416_D10_SD","ACE_HK416_D14_SD","ACE_KAC_PDW","BAF_L85A2_RIS_SUSAT",
        "ACE_M1014_EOTECH","ACE_M14_ACOG","ACE_M16A4_IRON","ACE_M4","ACE_M4_AIM","ACE_M4_AIM_F","ACE_M4_F","ACE_M4_EOTECH","ACE_M4_EOTECH_F","M4A1","M4A1_AIM","ACE_M4A1_AIM_F","ACE_M4A1_AIM_SD",
        "ACE_M4A1_AIM_SD_F","ACE_M4A1_F","ACE_M4A1_EOTECH","ACE_M4A1_EOTECH_F","SCAR_L_CQC","ACE_MP7","ACE_UMP45_AIM","ACE_UMP45_SD","ACRE_PRC119","ACE_MAP_TOOLS","GLOCK17_EP1","COLT1911","ACE_L9A1","M9SD",
        "ACE_MINEDETECTOR_US","ACE_YARDAGE450",
        
        "ACE_AEK_971","ACE_AEK_971_TGP_CLN","ACE_AEK_971_SHAHIN","ACE_AEK_971_1PN100","ACE_AEK_971_1P78","ACE_AEK_971_GP_1P63","ACE_AEK_971_1P63","ACE_AEK_971_GP","ACE_AEK_973S",
        "ACE_AEK_973S_SHAHIN","ACE_AEK_973S_TGP_CLN","ACE_AEK_973S_1PN100","ACE_AEK_973S_1P78","ACE_AEK_973S_GP_1P63","ACE_AEK_973S_1P63","ACE_AEK_973S_GP",
        
        "ACE_AK103_PSO","ACE_AK104_PSO","ACE_AK105_PSO","AK_107_PSO","ACE_AK74M_TWS","ACE_AK74M_TWS_FL_F","ACE_AK74M_TWS_FL","ACE_AK74M_NSPU","ACE_AK74M_NSPU_FL","ACE_AK74M_NSPU_FL_F","ACE_AK74M_PSO",
        "ACE_AK74M_PSO_FL","ACE_AK74M_PSO_FL_F","ACE_AK74M_SD_TWS","ACE_AK74M_SD_TWS_F","ACE_AK74M_SD_NSPU","ACE_AK74M_SD_NSPU_F","ACE_AK74M_SD_PSO","ACE_AK74M_SD_PSO_F","AKS_GOLD","AKS_74_GOSHAWK",
        "AKS_74_KOBRA","AKS_74_NSPU","AKS_74_PSO","ACE_AKS74P_PSO","ACE_VAL_KOBRA","ACE_VAL_PSO","ACE_VAL","FN_FAL_ANPVS4","G36A","G36K","G36A_CAMO","ACE_G36A2","ACE_G36A2_D_F","ACE_G36A2_D","ACE_G36A2_F",
        "G36C_CAMO","G36_C_SD_CAMO","G36_C_SD_EOTECH","G36K_CAMO","ACE_G36K_IRON_D","ACE_G36K_EOTECH","ACE_G36K_EOTECH_D","ACE_GR1","ACE_GR1SP","ACE_GR1SD","ACE_GR1SDSP","ACE_OC14","ACE_OC14SP","ACE_OC14SD","ACE_OC14SDSP",
        "ACE_HK416_D10_COMPM3","ACE_HK416_D10_COMPM3_SD","ACE_HK416_D10_HOLO","ACE_HK416_D10_AIM","ACE_HK416_D14_ACOG_PVS14","ACE_HK416_D14_COMPM3","ACE_HK416_D14_TWS","ACE_HK417_MICRO","ACE_HK417_EOTECH_4X",
        "ACE_HK417_SHORTDOT","BAF_L85A2_RIS_ACOG","BAF_L85A2_RIS_CWS","BAF_L85A2_RIS_HOLO","M16A4","ACE_M16A4_EOT","M16A4_ACG","ACE_M4_ACOG_PVS14","ACE_M4_ACOG_PVS14_F","ACE_M4_ACOG","ACE_M4_ACOG_F",
        "ACE_M4A1_ACOG_PVS14","ACE_M4A1_ACOG_PVS14_F","ACE_M4A1_EOT_SD","ACE_M4A1_EOT_SD_F","ACE_SOC_M4A1_EOTECH_4X","ACE_SOC_M4A1_EOTECH_4X_F","ACE_SOC_M4A1_EOTECH","ACE_SOC_M4A1_EOTECH_F","M4A1_AIM_SD_CAMO",
        "ACE_SOC_M4A1_AIM","ACE_SOC_M4A1_AIM_SD","ACE_M4A1_ACOG","ACE_M4A1_ACOG_F","ACE_M4A1_ACOG_SD","ACE_M4A1_ACOG_SD_F","ACE_SOC_M4A1_SD_9","ACE_SOC_M4A1_SHORTDOT_F","ACE_SOC_M4A1_SHORTDOT_SD_F",
        "ACE_SOC_M4A1_SHORTDOT_SD","ACE_SOC_M4A1_SHORTDOT","ACE_SOC_M4A1_EOT_SD","ACE_SOC_M4A1_EOT_SD_F","ACE_SOC_M4A1","ACE_SOC_M4A1_TWS_F","ACE_SOC_M4A1_TWS","M4A3_CCO_EP1","M8_CARBINE","M8_COMPACT",
        "M8_COMPACT_PMC","M8_CARBINE_PMC","M8_HOLO_SD","M8_TWS","M8_TWS_SD","M4A1_AIM_CAMO","SCAR_L_CQC_CCO_SD","SCAR_L_CQC_HOLO","SCAR_L_STD_HOLO","SCAR_L_STD_MK4CQT","SCAR_H_CQC_CCO","SCAR_H_CQC_CCO_SD",
        "ACE_SCAR_H_STD_SPECT",
        "ACE_MP7_RSAS","ACE_UMP45_AIM_SD","ACE_FLAREGUN","ACE_GLOCK18","ACE_P8","REVOLVER_GOLD_EP1","ACE_P226","ACE_USP","ACE_USPSD",
        "EVO_ACR","EVO_MRAD_ACR","EVO_SD_ACR","CZ805_A1_ACR","CZ805_A2_SD_ACR","CZ805_A2_ACR",
        
        //mods
        //RH416
        "RH_HK416","RH_HK416AIM","RH_HK416ACOG","RH_HK416EOTECH","RH_HK416SD","RH_HK416SDAIM","RH_HK416SDEOTECH","RH_HK416S","RH_HK416SAIM","RH_HK416SEOTECH","RH_HK416SACOG",
        "RH_HK417","RH_HK417AIM","RH_HK417ACOG","RH_HK417EOTECH","RH_HK417SD","RH_HK417SDAIM","RH_HK417SDACOG","RH_HK417SDEOTECH","RH_HK417S","RH_HK417SAIM","RH_HK417SACOG","RH_HK417SEOTECH",
        "RH_MAS","RH_MASACOG","RH_MASAIM","RH_MASEOTECH","RH_MASB","RH_MASBACOG","RH_MASBAIM","RH_MASBEOTECH","RH_MASSD","RH_MASSDACOG","RH_MASSDAIM","RH_MASSDEOTECH","RH_MASBSD","RH_MASBSDACOG",
        "RH_MASBSDAIM","RH_MASBSDEOTECH","RH_ACR","RH_ACRACOG","RH_ACRAIM","RH_ACREOTECH","RH_ACRB","RH_ACRBACOG","RH_ACRBAIM","RH_ACRBEOTECH","RH_CTAR21","RH_CTAR21M","RH_STAR21",

        //TMT HK33
        "TMTR_HK33","TMTR_HK33_HOLO","TMTR_HK33_ZF",

        //RH SMG
        "RH_UZI","RH_UZIM","RH_UZISD","RH_UMP","RH_UMPAIM","RH_UMPEOT","RH_UMPRFX","RH_UMPSD","RH_UMPSDAIM","RH_UMPSDEOT","RH_UMPSDRFX",
        "RH_TMP","RH_TMPAIM","RH_TMPEOT","RH_TMPSD","RH_TMPSDAIM","RH_TMPSDEOT","RH_P90","RH_P90I","RH_P90AIM","RH_P90EOT","RH_P90SD","RH_P90ISD","RH_P90SDAIM","RH_P90SDEOT",
        "RH_MP7","RH_MP7P","RH_MP7AIM","RH_MP7EOT", "RH_MP5SD6","RH_MP5SD6AIM","RH_MP5SD6EOT","RH_MP5SD6RFX","RH_MP5K","RH_MP5KP","RH_MP5KPDW","RH_MP5KPDWAIM","RH_MP5KPDWEOT","RH_MP5KPDWRFX",
        "RH_MP5A5","RH_MP5A5AIM","RH_MP5A5EOT","RH_MP5A5RFX","RH_MP5A5RIS","RH_MP5A5RISAIM","RH_MP5A5RISEOT","RH_MP5A5RISRFX",
        "RH_MP5A4","RH_MP5A4AIM","RH_MP5A4EOT","RH_MP5A4RFX","RH_MAC10","RH_MAC10P","RH_KRISS","RH_KRISSAIM","RH_KRISSEOT","RH_KRISSRFX","RH_KRISSSD","RH_KRISSSDAIM","RH_KRISSSDEOT","RH_KRISSSDRFX",
        "RH_HK53","RH_HK53AIM","RH_HK53EOT","RH_HK53RFX",

        //RH M4
        "RH_M16A4","RH_M16A4ACOG","RH_M16A4AIM","RH_M16A4EOTECH","RH_M16A3","RH_M16A3AIM","RH_M16A3S","RH_M16A3C","RH_M16A3CS","RH_M16A2","RH_M16A2AIM","RH_M16A2S","RH_M16A1","RH_M16A1S",
        "RH_M4A1","RH_M4A1R","RH_M4A1AIM","RH_M4A1EOTECH","RH_M4A1ACOG","RH_M4SD","RH_M4SDAIM","RH_M4SDACOG","RH_M4SDEOTECH","RH_M4AIM_WDL","RH_M4SDAIM_WDL","RH_M4","RH_M4R",
        "RH_M4AIM","RH_M4EOTECH","RH_M4ACOG","RH_M4SBR","RH_M4SBRAIM","RH_M4SBREOTECH","RH_M4SBRACOG","RH_M4M","RH_M4MAIM","RH_M4MEOTECH","RH_M4MACOG","RH_AR10","RH_AR10S",

        //RH M14
        "RH_M14","RH_M14ACOG","RH_M14AIM","RH_M14EOT","RH_SC2","RH_SC2ACOG","RH_SC2AIM","RH_SC2EOT","RH_SC2SHD","RH_M1S","RH_M1SACOG","RH_M1SAIM","RH_M1SEOT","RH_M1SSHD",
        "RH_M1ST","RH_M1STACOG","RH_M1STAIM","RH_M1STEOT","RH_M1STSHD",

        //Hz M16A3 RAS
        "HZ_M16A3RAS","HZ_M16A3RAS_CCO","HZ_M16A3RAS_EOT","HZ_M16A3RAS_RCO",
         
        "C1987_G3","GMS_K98","HKG3A6","HKG3A4","G36C_AIM_JEY","G36C_AIM_SD_JEY","G36C_AIM3X_JEY","G36C_AIM3X_SD_JEY","G36C_D_AIM_JEY",
				"G36C_D_AIM_SD_JEY","G36C_D_AIM3X_JEY","G36C_D_AIM3X_SD_JEY"
         
        ];
         
        //the rest  
        [] call compile preprocessfilelinenumbers "HZ\Hz_scripts\Hz_role_limitations.sqf";
     
    };
            
};

waituntil {sleep 1; !isnull player};

if((getplayeruid player) in Hz_temp_non_supervisor_PMC_permissions) then {
    
    player setvariable ["PMC",true,true];
                
    [] call compile preprocessfilelinenumbers "HZ\Hz_scripts\Hz_role_limitations.sqf";    
        
} else {

    //sloppy but should do for now...    
    if (_playertype == "PUBLIC" || _playertype == "WHITELIST") then {

        AT = false;
        GR = false;
        DM = false;
        MED = false;
        MG = false;
        AA = false;
        AT_A = false;
        GR_A = false;
        DM_A = false;
        MED_A = false;
        MG_A = false;
        AA_A = false;

        TANK = false;
        IFV = false;
        H_P = false;
        P_P = false;
        ARTY = false;

        SNIPER = false;
        SNIPER_A = false;
        FAC = false;
        PARA = false;
        Hz_roles_initdone = true;

    };

};


if([] call Hz_func_isSupervisor) then {player setvariable ["PMC",true,true];};
if((getplayeruid player) in Hz_Officers) then {player setvariable ["TL",true,true];};

if(hz_debug) exitwith {};

//mutex lock for weapons check at weapons store
Hz_wep_restriction_lock = false;

while {true} do {
    
    while {alive player} do {
  
        sleep 5;
  
        // _backwep = [player] call ACE_fnc_WeaponOnBackName;
        //  sleep 0.1;
        // _ruckitems = [player] call ACE_fnc_RuckWeaponsList;
        //  sleep 0.1;
        //_backpackweps = [];
        // if((count _ruckitems) > 0) then {_backpackweps = _ruckitems select 0;};
        _allweps = (weapons player);
        //_allweps = _allweps + _backpackweps;
        // sleep 0.1;
        // if(_backwep != "") then {_allweps set [count _allweps, _backwep];};
        _spitweps = [];
  
        //_start = diag_tickTime;
  
        {
            _wep = _x;
      
            if("ACRE_BaseRadio" in ([(configFile >> "CfgWeapons" >> _wep), true] call BIS_fnc_returnparents)) then {
      
                //ACRE classname correction
                if ("ACRE_PRC148_UHF" in ([(configFile >> "CfgWeapons" >> _wep), true] call BIS_fnc_returnparents) ) then {_wep = "ACRE_PRC148_UHF";} else { 
                    if ("ACRE_PRC148" in ([(configFile >> "CfgWeapons" >> _wep), true] call BIS_fnc_returnparents) ) then {_wep = "ACRE_PRC148";} else {
                        if ("ACRE_PRC343" in ([(configFile >> "CfgWeapons" >> _wep), true] call BIS_fnc_returnparents) ) then {_wep = "ACRE_PRC343";} else {
                            if ("ACRE_PRC117F" in ([(configFile >> "CfgWeapons" >> _wep), true] call BIS_fnc_returnparents) ) then {_wep = "ACRE_PRC117F";} else {
                                if ("ACRE_PRC119" in ([(configFile >> "CfgWeapons" >> _wep), true] call BIS_fnc_returnparents) ) then {_wep = "ACRE_PRC119";};
      
            };};};};};
      
            if (!((toupper _wep) in Hz_client_allowed_weps)) then {_spitweps set [count _spitweps, _x];};
            sleep 0.01;
        }foreach _allweps;

        if (((count _spitweps) > 0) && !Hz_wep_restriction_lock) then {_spitweps call Hz_func_spitoutweps;};
  
        // hint format ["%1",diag_tickTime - _start];
   
        if((vehicle player)!= player) then {call Hz_func_check_vehicle;};  
   
    };         
                
    sleep 10;   

};