private _relationsMultiplier = Hz_econ_sideRelationsPriceMultipler;

private ["_return","_item"];

_item = toupper _this;

_return = switch (_item) do {
    		
//Uniforms
case "TRYK_B_TRYK_3C_T": {767.3};
case "TRYK_U_B_ACU": {455.95};
case "TRYK_U_B_ACUTSHIRT": {455.95};
case "TRYK_U_B_ARO1_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_ARO1R_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_ARO1_BLK_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_ARO1_BLK_R_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_ARO1_CBR_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_ARO1_CBR_R_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_ARO1_GR_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_ARO1_GR_R_COMBATUNIFORM" :{1157.8};
case "TRYK_U_B_ARO1_GRY_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_ARO1_GRY_R_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_ARO2_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_ARO2R_COMBATUNIFORM": {1157.8};
case "TRYK_DMARPAT_T": {1150};
case "TRYK_C_AOR2_T": {1157.8};
case "TRYK_U_B_AOR2_T": {1157.8};
case "TRYK_U_B_AOR2_BLK_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_AOR2_BLK_R_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_AOR2_GRY_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_AOR2_GRY_R_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_AOR2_OD_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_AOR2_OD_R_COMBATUNIFORM": {1157.8};
case "TRYK_U_B_PCUHSW8": {395.22};
case "TRYK_U_B_PCUHSW3": {395.22};
case "TRYK_U_B_PCUHSW9": {395.22};
case "TRYK_U_B_PCUHSW7": {395.22};
case "TRYK_U_B_BLKBLK_COMBATUNIFORM": {455.95};
case "TRYK_U_B_BLKBLK_R_COMBATUNIFORM": {455.95};
case "TRYK_U_B_BLKOCP_COMBATUNIFORM": {560.95};
case "TRYK_U_BLKOCP_R_COMBATUNIFORMTSHIRT": {560.95};
case "TRYK_U_B_BLOD_T": {477.30};
case "TRYK_U_B_BLKTAN_COMBATUNIFORM": {767};
case "TRYK_U_B_BLKTANR_COMBATUNIFORMTSHIRT": {767};
case "TRYK_U_B_BLTAN_T": {767};
case "TRYK_U_B_C01_TSIRT": {767};
case "TRYK_U_B_C02_TSIRT": {767};
case "TRYK_U_B_3CR": {767.3};
case "TRYK_U_B_3C": {767.3};
case "TRYK_U_B_BLK3CD_TSHIRT": {767.3};
case "TRYK_U_B_BLK3CD": {767.3};
case "TRYK_U_B_BLKTAN": {767.3};
case "TRYK_U_B_BLKTAN_TSHIRT": {767.3};
case "TRYK_U_B_BLK_TSHIRT": {767.3};
case "TRYK_U_B_BLK": {767.3};
case "TRYK_U_B_BLK_OD_TSHIRT": {767.3};
case "TRYK_U_B_BLK_OD": {767.3};
case "TRYK_U_B_OD_BLK_2": {767.3};
case "TRYK_U_B_OD_BLK": {767.3};
case "TRYK_U_B_ODTAN": {767.3};
case "TRYK_U_B_ODTAN_TSHIRT": {767.3};
case "TRYK_U_B_SAGE_TSHIRT": {767.3};
case "TRYK_U_B_BLK_TAN_2": {767.3};
case "TRYK_U_B_BLK_TAN_1": {767.3};
case "TRYK_U_B_3CD_DELTA_BDU": {455.95};
case "TRYK_U_B_3CD_DELTA_BDUTSHIRT": {455.95};
case "TRYK_U_B_3CD_RANGER_BDU": {455.95};
case "TRYK_U_B_3CD_RANGER_BDUTSHIRT": {455.95};
case "TRYK_U_B_3CD_BLK_BDUTSHIRT": {455.95};
case "TRYK_U_BDU_3CD_BLK_BDUTSHIRT2": {455.95};
case "TRYK_U_B_FLEECE": {462};
case "TRYK_U_B_FLEECE_UCP": {357};
case "TRYK_U_B_GRTAN_COMBATUNIFORM": {455.95};
case "TRYK_U_B_GRTANR_COMBATUNIFORMTSHIRT": {455.95};
case "TRYK_U_B_GRYOCP_COMBATUNIFORM": {560.95};
case "TRYK_U_B_GRYOCP_R_COMBATUNIFORMTSHIRT": {560.95};
case "TRYK_OVERALL_SAGE_BLKBOOTS_NK_BLK2": {360.27};
case "TRYK_OVERALL_NOK_FLESH": {360.27};
case "TRYK_OVERALL_SAGE_BLKBOOTS_NK": {360.27};
case "TRYK_OVERALL_SAGE_BLKBOOTS_NK_BLK": {360.27};
//case "TRYK_OVERALL_FLESH": {400.95};
case "TRYK_OVERALL_SAGE": {400.95};
case "TRYK_OVERALL_SAGE_BLKBOOTS": {400.95};
case "TRYK_U_B_MARPAT_DESERT_TSHIRT": {455.95};
case "TRYK_U_B_MARPAT_DESERT": {455.95};
case "TRYK_U_B_MARPAT_DESERT": {455.95};
case "TRYK_U_B_MARPAT_DESERT2_TSHIRT": {455.95};
case "TRYK_U_B_MARPAT_DESERT2": {455.95};
case "TRYK_U_B_MARPAT_WOOD_TSHIRT": {455.95};
case "TRYK_U_B_MARPAT_WOOD": {455.95};
case "TRYK_U_B_MARPAT_WOOD_COMBATUNIFORM": {455.95};
case "TRYK_U_B_MARPAT_WOOD_COMBATUNIFORMTSHIRT": {455.95};
case "TRYK_U_B_MTP_COMBATUNIFORM": {665};
case "TRYK_U_B_MTP_R_COMBATUNIFORM": {665};
case "TRYK_B_TRYK_MTP_T": {515};
case "TRYK_U_B_MTP_BLK_COMBATUNIFORM": {805};
case "TRYK_U_B_MTP_BLK_R_COMBATUNIFORM": {805};
case "TRYK_U_B_NATO_OCP_COMBATUNIFORM": {665};
case "TRYK_U_B_NATO_OCPD_COMBATUNIFORM": {665};
case "TRYK_U_B_NATO_OCP_R_COMBATUNIFORM": {665};
case "TRYK_U_B_NATO_OCPD_R_COMBATUNIFORM": {665};
case "TRYK_B_TRYK_OCP_D_T": {515};
case "TRYK_B_TRYK_OCP_T": {515};
case "TRYK_U_B_NATO_OCP_C_BLK_COMBATUNIFORM": {665};
case "TRYK_U_B_NATO_OCP_BLK_COMBATUNIFORM": {665};
case "TRYK_U_B_NATO_OCP_BLK_C_R_COMBATUNIFORM": {665};
case "TRYK_U_B_NATO_OCP_BLK_R_COMBATUNIFORM": {665};
case "TRYK_U_B_OD_OD_COMBATUNIFORM": {455.95};
case "TRYK_U_B_OD_OD_R_COMBATUNIFORM": {455.95};
case "TRYK_U_B_ODTAN_COMBATUNIFORM": {455.95};
case "TRYK_U_B_ODTANR_COMBATUNIFORMTSHIRT": {455.95};
case "TRYK_U_BTS_PCUS": {529.95};
case "TRYK_U_BTS_PCUGS": {509.95};
case "TRYK_U_BTS_GRYGRY_PCUS": {529.95};
case "TRYK_U_BTS_UCP_PCUS": {424.95};
case "TRYK_U_BTS_WOOD_PCUS": {424.95};
case "TRYK_U_BTS_PCUODS": {529.95};
case "TRYK_U_B_PCUHS": {395.22};
case "TRYK_U_B_PCUGHS": {395.22};
case "TRYK_U_B_PCUODHS": {395.22};
case "TRYK_U_B_PCUGS_BLK_R": {427.22};
case "TRYK_U_B_PCUGS_GRY_R": {427.22};
case "TRYK_U_B_PCUGS_OD_R": {427.22};
case "TRYK_U_B_PCUS_R": {395.22};
case "TRYK_U_B_PCUS": {395.22};
case "TRYK_U_B_PCUGS_BLK": {407.22};
case "TRYK_U_B_PCUGS": {395.22};
case "TRYK_U_B_GRY_PCUS_R": {290.22};
case "TRYK_U_B_GRY_PCUS": {290.22};
case "TRYK_U_B_UCP_PCUS_R": {290.22};
case "TRYK_U_B_UCP_PCUS": {290.22};
case "TRYK_U_B_WOOD_PCUS_R": {290.22};
case "TRYK_U_B_WOOD_PCUS": {290.22};
case "TRYK_U_B_PCUGS_GRY": {407.22};
case "TRYK_U_B_PCUODS": {395.22};
case "TRYK_U_B_PCUGS_OD": {407.22};
case "TRYK_U_B_AOR1_ROLLUP_COMBATUNIFORM": {860};
case "TRYK_U_B_AOR2_ROLLUP_COMBATUNIFORM": {860};
case "TRYK_U_B_BLK_OD_ROLLUP_COMBATUNIFORM": {477.3};
case "TRYK_U_B_BLK_TAN_ROLLUP_COMBATUNIFORM": {477.3};
case "TRYK_U_B_WH_BLK_ROLLUP_COMBATUNIFORM": {477.3};
case "TRYK_U_B_WH_OD_ROLLUP_COMBATUNIFORM": {477.3};
case "TRYK_U_B_WH_TAN_ROLLUP_COMBATUNIFORM": {477.3};
case "TRYK_U_B_SAGE_T": {515};
case "TRYK_SHIRTS_DENIM_BK": {377.27};
case "TRYK_SHIRTS_DENIM_BL": {337.27};
case "TRYK_SHIRTS_DENIM_BWH": {337.27};
case "TRYK_SHIRTS_DENIM_OD": {337.27};
case "TRYK_SHIRTS_DENIM_R": {337.27};
case "TRYK_SHIRTS_DENIM_RED2": {337.27};
case "TRYK_SHIRTS_DENIM_WH": {337.27};
case "TRYK_SHIRTS_DENIM_WHB": {337.27};
case "TRYK_SHIRTS_DENIM_YLB": {337.27};
case "TRYK_SHIRTS_DENIM_OD_SLEEVE": {377.27};
case "TRYK_SHIRTS_DENIM_YLB_SLEEVE": {377.27};
case "TRYK_SHIRTS_DENIM_BK_SLEEVE": {377.27};
case "TRYK_SHIRTS_DENIM_BL_SLEEVE": {377.27};
case "TRYK_SHIRTS_DENIM_BWH_SLEEVE": {377.27};
case "TRYK_SHIRTS_DENIM_R_SLEEVE": {377.27};
case "TRYK_SHIRTS_DENIM_RED2_SLEEVE": {377.27};
case "TRYK_SHIRTS_DENIM_WH_SLEEVE": {377.27};
case "TRYK_SHIRTS_DENIM_WHB_SLEEVE": {377.27};
case "TRYK_SHIRTS_PAD_BK": {280.27};
case "TRYK_SHIRTS_BLK_PAD_BK": {280.27};
case "TRYK_SHIRTS_OD_PAD_BK": {280.27};
case "TRYK_SHIRTS_TAN_PAD_BK": {280.27};
case "TRYK_SHIRTS_PAD_BL": {280.27};
case "TRYK_SHIRTS_BLK_PAD_BL": {280.27};
case "TRYK_SHIRTS_OD_PAD_BL": {280.27};
case "TRYK_SHIRTS_TAN_PAD_BL": {280.27};
case "TRYK_SHIRTS_PAD_BLW": {280.27};
case "TRYK_SHIRTS_BLK_PAD_BLW": {280.27};
case "TRYK_SHIRTS_OD_PAD_BLW": {280.27};
case "TRYK_SHIRTS_TAN_PAD_BLW": {280.27};
case "TRYK_SHIRTS_PAD_BLU3": {280.27};
case "TRYK_SHIRTS_BLK_PAD_BLU3": {280.27};
case "TRYK_SHIRTS_OD_PAD_BLU3": {280.27};
case "TRYK_SHIRTS_TAN_PAD_BLU3": {280.27};
case "TRYK_SHIRTS_PAD": {280.27};
case "TRYK_SHIRTS_BLK_PAD": {280.270};
case "TRYK_SHIRTS_OD_PAD": {280.27};
case "TRYK_SHIRTS_TAN_PAD": {280.27};
case "TRYK_SHIRTS_PAD_RED2": {280.27};
case "TRYK_SHIRTS_BLK_PAD_RED2": {280.27};
case "TRYK_SHIRTS_OD_PAD_RED2": {280.27};
case "TRYK_SHIRTS_TAN_PAD_RED2": {280.27};
case "TRYK_SHIRTS_PAD_YEL": {280.27};
case "TRYK_SHIRTS_BLK_PAD_YEL": {280.27};
case "TRYK_SHIRTS_OD_PAD_YEL": {280.27};
case "TRYK_SHIRTS_TAN_PAD_YEL": {280.27};
case "TRYK_U_B_SNOW_COMBATUNIFORM": {-1};
case "TRYK_U_B_SNOWT": {-1};
case "TRYK_T_PAD": {240};
case "TRYK_U_PAD_HOOD_CSATBLK": {327};
case "TRYK_U_PAD_HOOD_BLOD": {327};
case "TRYK_U_PAD_HOOD_BLK": {327};
case "TRYK_U_PAD_HOOD_CL_BLK": {327};
case "TRYK_U_PAD_HOOD_BKT2": {327};
case "TRYK_U_NOHOODPCU_GRY": {327};
case "TRYK_U_PAD_HOOD_ODBK": {327};
case "TRYK_U_PAD_HOOD_CL": {327};
case "TRYK_U_PAD_HOOD_TAN": {327};
case "TRYK_HOODIE_3C": {327};
case "TRYK_HOODIE_FR": {337};
case "TRYK_HOODIE_BLK": {442};
case "TRYK_HOODIE_WOOD": {327};
case "TRYK_U_HOOD_MC": {327};
case "TRYK_U_HOOD_NC": {327};
case "TRYK_T_BLK_PAD": {327};
case "TRYK_T_CSAT_PAD": {327};
case "TRYK_T_OD_PAD": {327};
case "TRYK_T_TAN_PAD": {327};
case "TRYK_T_T2_PAD": {327};
case "TRYK_U_DENIM_HOOD_3C": {404};
case "TRYK_U_DENIM_HOOD_BLK": {404};
case "TRYK_U_DENIM_HOOD_MC": {404};
case "TRYK_U_DENIM_HOOD_NC": {404};
case "TRYK_U_DENIM_JERSEY_BLK": {403};
case "TRYK_U_DENIM_JERSEY_BLU": {403};
case "TRYK_U_PAD_J_BLK": {406};
case "TRYK_U_PAD_J": {406};
case "TRYK_U_TAKI_BL": {255};
case "TRYK_U_TAKI_BLK": {255};
case "TRYK_U_TAKI_COY": {255};
case "TRYK_U_TAKI_WH": {255};
case "TRYK_U_TAKI_G_BL": {312};
case "TRYK_U_TAKI_G_BLK": {312};
case "TRYK_U_TAKI_G_COY": {312};
case "TRYK_U_TAKI_G_WH": {312};
case "TRYK_T_CAMO_3C_BG": {335};
case "TRYK_T_CAMO_DESERT_MARPAT_BG": {345};
case "TRYK_T_CAMO_WOOD_BG": {335};
case "TRYK_T_CAMO_WOOD_MARPAT_BG": {345};
case "TRYK_T_CAMO_3C": {320};
case "TRYK_T_CAMO_DESERT_MARPAT": {330};
case "TRYK_T_CAMO_TAN": {320};
case "TRYK_T_CAMO_WOOD": {320};
case "TRYK_T_CAMO_WOOD_MARPAT": {330};
case "TRYK_U_B_WOODTAN_COMBATUNIFORM": {456};
case "TRYK_U_B_WOODTANR_COMBATUNIFORMTSHIRT": {456};
case "TRYK_SUITS_BLK_F": {460};
case "TRYK_SUITS_BR_F": {460};
case "TRYK_U_B_BLK_T_BG_BK": {320};
case "TRYK_U_B_RED_T_BG_BR": {320};
case "TRYK_U_B_BLK_T_BG_WH": {320};
case "TRYK_U_B_BLK_T_BK": {272};
case "TRYK_U_B_RED_T_BR": {272};
case "TRYK_U_B_BLK_T_WH": {272};
case "TRYK_U_B_DENIM_T_BG_BK": {312};
case "TRYK_U_B_DENIM_T_BG_WH": {312};
case "TRYK_U_B_DENIM_T_BK": {272};
case "TRYK_U_B_DENIM_T_WH": {272};
case "TRYK_ZARATAKI": {50};
case "TRYK_ZARATAKI2": {50};
case "TRYK_ZARATAKI3": {50};
case "TRYK_U_B_TANOCP_COMBATUNIFORM": {560.95};
case "TRYK_U_B_TANOCP_R_COMBATUNIFORMTSHIRT": {560.95};
case "TRYK_U_B_TANTAN_COMBATUNIFORM": {456};
case "TRYK_U_B_TANTAN_R_COMBATUNIFORM": {456};
case "TRYK_U_B_JSDF_COMBATUNIFORM": {456};
case "TRYK_U_B_JSDF_COMBATUNIFORMTSHIRT": {456};
case "TRYK_U_B_NATO_UCP_COMBATUNIFORM": {456};
case "TRYK_U_B_NATO_UCP_R_COMBATUNIFORM": {456};
case "TRYK_B_TRYK_UCP_T": {477};
case "TRYK_U_B_NATO_UCP_GRY_COMBATUNIFORM": {805};
case "TRYK_U_B_NATO_UCP_GRY_R_COMBATUNIFORM": {805};
case "TRYK_B_USMC_R": {1150};
case "TRYK_B_USMC_R_ROLL": {1150};
case "TRYK_U_B_PCUHSW5": {-1};
case "TRYK_U_B_PCUHSW2": {-1};
case "TRYK_U_B_PCUHSW": {-1};
case "TRYK_U_B_PCUHSW6": {-1};
case "TRYK_U_B_PCUHSW4": {-1};
case "TRYK_U_B_WOODLAND": {665};
case "TRYK_U_B_WOODLAND_TSHIRT": {665};
case "TRYK_U_B_WOOD_COMBATUNIFORM": {456};
case "TRYK_U_B_WOODR_COMBATUNIFORMTSHIRT": {456};
case "TRYK_U_B_WDL_GRY_COMBATUNIFORM": {805};
case "TRYK_U_B_WDL_GRY_R_COMBATUNIFORM": {805};
case "TRYK_U_B_WOOD_T": {515};
case "TRYK_U_B_WOOD3C_COMBATUNIFORM": {456};
case "TRYK_U_B_WOOD3C_COMBATUNIFORMTSHIRT": {456};
case "TRYK_U_B_WOOD_MARPAT_COMBATUNIFORM": {456};
case "TRYK_U_B_WOOD_MARPAT_COMBATUNIFORMTSHIRT": {456};



//Vests
case "TRYK_V_BULLETPROOF_BL": {230};
case "TRYK_V_BULLETPROOF_BLK": {230};
case "TRYK_V_BULLETPROOF": {230};
case "TRYK_V_ARMORVEST_AOR2_2": {2074*_relationsMultiplier};
case "TRYK_V_ARMORVEST_BROWN2": {2074*_relationsMultiplier};
case "TRYK_V_ARMORVEST_CBR2": {2074*_relationsMultiplier};
case "TRYK_V_ARMORVEST_KHK2": {2074*_relationsMultiplier};
case "TRYK_V_ARMORVEST_AOR1_2": {2074*_relationsMultiplier};
case "TRYK_V_ARMORVEST_COYO2": {2074*_relationsMultiplier};
case "TRYK_V_ARMORVEST_DELTA2": {2074*_relationsMultiplier};
case "TRYK_V_ARMORVEST_GREEN2": {2074*_relationsMultiplier};
case "TRYK_V_ARMORVEST_RANGER2": {2074*_relationsMultiplier};
case "TRYK_V_ARMORVEST_TAN2": {2074*_relationsMultiplier};
case "TRYK_V_ARMORVEST_AOR1": {1729*_relationsMultiplier};
case "TRYK_V_ARMORVEST_AOR2": {1729*_relationsMultiplier};
case "TRYK_V_ARMORVEST_BROWN": {1729*_relationsMultiplier};
case "TRYK_V_ARMORVEST_CBR": {1729*_relationsMultiplier};
case "TRYK_V_ARMORVEST_COYO": {1729*_relationsMultiplier};
case "TRYK_V_ARMORVEST_DELTA": {1729*_relationsMultiplier};
case "TRYK_V_ARMORVEST_GREEN": {1729*_relationsMultiplier};
case "TRYK_V_ARMORVEST_KHK": {1729*_relationsMultiplier};
case "TRYK_V_ARMORVEST_RANGER": {1729*_relationsMultiplier};
case "TRYK_V_ARMORVEST_TAN": {1729*_relationsMultiplier};
case "TRYK_V_PLATECARRIER_COYO": {2324*_relationsMultiplier};
case "TRYK_V_PLATECARRIER_ACU": {2324*_relationsMultiplier};
case "TRYK_V_PLATECARRIER_WOOD": {2324*_relationsMultiplier};
case "TRYK_V_PLATECARRIER_COYO_L": {1729*_relationsMultiplier};
case "TRYK_V_PLATECARRIER_ACU_L": {1729*_relationsMultiplier};
case "TRYK_V_PLATECARRIER_BLK": {2324*_relationsMultiplier};
case "TRYK_V_PLATECARRIER_BLK_L": {1729*_relationsMultiplier};
case "TRYK_V_PLATECARRIER_WOOD_L": {1729*_relationsMultiplier};
case "TRYK_V_HARNES_BLK_L": {125};
case "TRYK_V_HARNES_OD_L": {125};
case "TRYK_V_HARNES_TAN_L": {125};
case "TRYK_V_IOTV_BLK": {755*_relationsMultiplier};
case "TRYK_V_TACVEST_COYO": {262};
case "TRYK_V_PLATECARRIER_JSDF": {2324*_relationsMultiplier};

case "CUP_V_B_RRV_MEDIC": {250};



//Rucks
case "TRYK_B_ALICEPACK": {86};
case "TRYK_B_ASSAULTPACK_MARPAT_DESERT": {170};
case "TRYK_B_ASSAULTPACK_MARPAT_WOOD": {170};
case "TRYK_B_ASSAULTPACK_TYPE2CAMO": {170};
case "TRYK_B_ASSAULTPACK_UCP": {170};
case "TRYK_B_COYOTEBACKPACK_BLK": {110};
case "TRYK_B_COYOTEBACKPACK": {110};
case "TRYK_B_COYOTEBACKPACK_OD": {110};
case "TRYK_B_COYOTEBACKPACK_WH": {-1};
case "TRYK_B_CARRYALL_JSDF": {50};
case "TRYK_B_CARRYALL_BLK": {50};
case "TRYK_B_CARRYALL_WH": {-1};
case "TRYK_B_CARRYAL_WOOD": {50};
case "TRYK_B_FIELDPACK_WOOD": {120};
case "TRYK_B_KITBAG_AAF": {100};
case "TRYK_B_KITBAG_BLK": {100};
case "TRYK_B_KITBAG_BASE": {100};
case "TRYK_B_KITBAG_BASE_JSDF": {100};
case "TRYK_B_MEDBAG": {170};
case "TRYK_B_MEDBAG_BK": {170};
case "TRYK_B_MEDBAG_OD": {170};
case "TRYK_B_MEDBAG_UCP": {170};
case "TRYK_B_BELT_AOR1": {617};
case "TRYK_B_BELT_AOR2": {617};
case "TRYK_B_BELT_BLK": {617};
case "TRYK_B_BELT_BR": {617};
case "TRYK_B_BELT_CYT": {617};
case "TRYK_B_BELT": {617};
case "TRYK_B_BELT_GR": {617};
case "TRYK_B_BELT_TAN": {617};
case "TRYK_B_BAF_BAG_BLK": {130};
case "TRYK_B_BAF_BAG_CYT": {130};
case "TRYK_B_BAF_BAG_MCAMO": {130};
case "TRYK_B_BAF_BAG_OD": {130};
case "TRYK_B_BAF_BAG_RGR": {130};
case "TRYK_B_TUBE_BLK": {173};
case "TRYK_B_TUBE_CYT": {173};
case "TRYK_B_TUBE_OD": {173};
case "TRYK_WINTER_PACK": {-1};

case "B_ASSAULTPACK_BLK": {170};
case "B_ASSAULTPACK_CBR": {170};
case "B_ASSAULTPACK_DGTL": {170};
case "B_ASSAULTPACK_RGR": {170};
case "B_ASSAULTPACK_OCAMO": {170};
case "B_ASSAULTPACK_KHK": {170};
case "B_ASSAULTPACK_MCAMO": {170};
case "B_ASSAULTPACK_SGG": {170};
case "B_CARRYALL_CBR": {50};
case "B_CARRYALL_OCAMO": {50};
case "B_CARRYALL_KHK": {50};
case "B_CARRYALL_MCAMO": {50};
case "B_CARRYALL_OLI": {50};
case "B_CARRYALL_OUCAMO": {50};
case "B_FIELDPACK_BLK": {120};
case "B_FIELDPACK_CBR": {120};
case "B_FIELDPACK_OCAMO": {120};
case "B_FIELDPACK_KHK": {120};
case "B_FIELDPACK_OLI": {120};
case "B_FIELDPACK_OUCAMO": {120};
case "B_KITBAG_CBR": {100};
case "B_KITBAG_RGR": {100};
case "B_KITBAG_MCAMO": {100};
case "B_KITBAG_SGG": {100};
case "B_TACTICALPACK_BLK": {130};
case "B_TACTICALPACK_RGR": {130};
case "B_TACTICALPACK_OCAMO": {130};
case "B_TACTICALPACK_MCAMO": {130};
case "B_TACTICALPACK_OLI": {130};
case "B_ASSAULTPACK_TNA_F": {170};
case "B_BERGEN_DGTL_F": {180};
case "B_BERGEN_HEX_F": {180};
case "B_BERGEN_MCAMO_F": {180};
case "B_BERGEN_TNA_F": {180};
case "B_CARRYALL_GHEX_F": {50};
case "B_FIELDPACK_GHEX_F": {120};
case "B_VIPERHARNESS_BLK_F": {240};
case "B_VIPERHARNESS_GHEX_F": {240};
case "B_VIPERHARNESS_HEX_F": {240};
case "B_VIPERHARNESS_KHK_F": {240};
case "B_VIPERHARNESS_OLI_F": {240};
case "B_VIPERLIGHTHARNESS_BLK_F": {200};
case "B_VIPERLIGHTHARNESS_GHEX_F": {200};
case "B_VIPERLIGHTHARNESS_HEX_F": {200};
case "B_VIPERLIGHTHARNESS_KHK_F": {200};
case "B_VIPERLIGHTHARNESS_OLI_F": {200};



//Headgear
case "TRYK_KIO_BALACLAVA": {8};
case "TRYK_H_BANDANA_H": {10};
case "TRYK_H_BANDANA_WIG": {10};
case "TRYK_H_BANDANA_WIG_G": {10};
case "TRYK_H_BOONIEHAT_3CD": {18};
case "TRYK_H_BOONIEHAT_AOR1": {18};
case "TRYK_H_BOONIEHAT_AOR2": {18};
case "TRYK_H_BOONIEHAT_CC": {18};
case "TRYK_H_BOONIEHAT_MARPAT_DESERT": {18};
case "TRYK_H_BOONIEHAT_MARPAT_WOOD": {18};
case "TRYK_H_BOONIEHAT_JSDF": {18};
case "TRYK_H_BOONIEHAT_WOOD": {18};


case "CUP_H_SLA_BERETRED": {20};
case "CUP_H_BERET_HIL": {20};
case "H_BERET_BLK": {20};


/*
case "TRYK_H_LHS_HEL_G": {-1};
*/



case "TRYK_H_EARMUFF": {595};
case "TRYK_ESS_CAP": {95};
case "TRYK_ESS_CAP_OD": {95};
case "TRYK_ESS_CAP_TAN": {95};



/*
case "TRYK_H_GHILLIE_OVER_GREEN": {-1};
case "TRYK_H_GHILLIE_TOP_GREEN": {-1};
case "TRYK_H_GHILLIE_TOP_HEADLESS_GREEN": {-1};
case "TRYK_H_GHILLIE_OVER": {-1};
case "TRYK_H_GHILLIE_TOP": {-1};
case "TRYK_H_GHILLIE_TOP_HEADLESS": {-1};
*/



case "TRYK_H_HEADSET2": {80};
case "TRYK_H_HEADSETCAP_GLASSES": {45};
case "TRYK_H_HEADSETCAP_BLK_GLASSES": {45};
case "TRYK_H_HEADSETCAP_OD_GLASSES" : {45};
case "TRYK_H_HEADSETCAP_BLK": {95};
case "TRYK_H_HEADSETCAP_OD": {95};
case "TRYK_H_HEADSETCAP": {95};

/*
case "TRYK_H_AOR1": {305};
case "TRYK_H_AOR2": {305};
case "TRYK_H_GR": {305};
case "TRYK_H_HELMET_3C": {525};
case "TRYK_H_HELMET_CC": {525};
case "TRYK_H_HELMET_MARPAT_DESERT": {525};
case "TRYK_H_HELMET_MARPAT_DESERT2": {525};
case "TRYK_H_HELMET_MARPAT_WOOD": {525};
case "TRYK_H_HELMET_ACU": {525};
case "TRYK_H_HELMET_WOOD": {525};
case "TRYK_H_PAKOL2": {-1};
case "TRYK_H_PAKOL": {-1};
case "TRYK_H_PASGT_BLK": {90};
case "TRYK_H_PASGT_COYO": {90};
case "TRYK_H_PASGT_OD": {90};
case "TRYK_H_PASGT_TAN": {90};
case "TRYK_H_DELTAHELM_NV": {-1};
*/


case "PO_H_M1_BLK": {70};
case "PO_H_M1_OLV_1": {70};
case "PO_H_M1_OLV_2": {70};
case "PO_H_M1_TAN": {70};
case "RHSGREF_HELMET_M1_BARE": {70};
case "RHSGREF_HELMET_M1_BARE_ALT01": {70};
case "RHSGREF_HELMET_M1_PAINTED": {70};
case "RHSGREF_HELMET_M1_PAINTED_ALT01": {70};

case "TRYK_R_CAP_BLK": {15};
case "TRYK_R_CAP_TAN": {15};
case "TRYK_R_CAP_OD_US": {15};
case "TRYK_R_CAP_BLK_GLASSES": {45};
case "TRYK_R_CAP_OD_GLASSES": {45};
case "TRYK_R_CAP_TAN_GLASSES": {45};



/*
case "TRYK_H_HELMET_SNOW": {-1};
*/



case "TRYK_H_WH": {-1};
case "TRYK_H_TACEARMUFF_H": {595};



/*
case "TRYK_H_HELMET_JSDF": {525};
*/



case "TRYK_H_WIG": {-1};



/*
case "TRYK_H_HELMET_WINTER": {-1};
case "TRYK_H_HELMET_WINTER_2": {-1};
*/



case "TRYK_H_WOOLHAT": {6};
case "TRYK_H_WOOLHAT_BR": {6};
case "TRYK_H_WOOLHAT_CU": {6};
case "TRYK_H_WOOLHAT_CW": {6};
case "TRYK_H_WOOLHAT_TAN": {6};
case "TRYK_H_WOOLHAT_WH": {6};

case "RHS_BOONIEHAT_M81": {18};
case "RHS_BOONIEHAT2_MARPATD": {18};
case "RHS_BOONIEHAT2_MARPATWD": {18};
case "RHS_BOONIEHAT_OCP": {18};
case "RHS_BOONIEHAT_UCP": {18};
case "RHSUSF_BOWMAN": {25};
case "RHSUSF_BOWMAN_CAP": {40};



/*
case "RHSUSF_PROTECH_HELMET": {32};
case "RHSUSF_PROTECH_HELMET_ESS":{112};
case "RHSUSF_PROTECH_HELMET_RHINO": {612};
case "RHSUSF_PROTECH_HELMET_RHINO_ESS": {692};
case "RHS_8POINT_MARPATD": {15};
case "RHS_8POINT_MARPATWD": {15};
*/



case "RHSUSF_PATROLCAP_OCP": {15};
case "RHSUSF_PATROLCAP_UCP": {15};

case "CUP_H_PMC_CAP_GREY": {15};
case "CUP_H_PMC_CAP_PRR_GREY": {95};
case "CUP_H_PMC_CAP_PRR_TAN": {95};
case "CUP_H_C_MAGA_01": {15};
case "CUP_H_PMC_CAP_TAN": {15};
case "CUP_H_C_TRACKIR_01": {15};
case "CUP_H_FR_CAP_HEADSET_GREEN": {40};



//Facewear
case "TRYK_KIO_BALACLAVA_BLK": {8};
case "TRYK_KIO_BALACLAVAS": {8};
case "TRYK_KIO_BALACLAVA_WH": {8};
case "TRYK_KIO_BALACLAVA_BLK_EAR": {603};
case "TRYK_KIO_BALACLAVA_EAR": {603};
case "TRYK_KIO_BALACLAVA_ESS": {88};
case "TRYK_BANDANA_G_": {10};
case "TRYK_US_ESS_GLASSES": {80};
case "TRYK_US_ESS_GLASSES_TAN_BLK": {80};
case "TRYK_US_ESS_GLASSES_BLK": {80};
case "TRYK_US_ESS_GLASSES_TAN": {80};
case "TRYK_US_ESS_GLASSES_WH": {80};
case "TRYK_HEADSET2_GLASSES": {80};
case "TRYK_HEADSET_GLASSES": {25};
case "TRYK_SHEMAGH_MESH": {10};
case "TRYK_SHEMAGH_G": {10};
case "TRYK_SHEMAGH": {10};
case "TRYK_SHEMAGH_WH": {10};
case "TRYK_SHEMAGH_EAR_G": {605};
case "TRYK_SHEMAGH_EAR_TAN": {605};
case "TRYK_SHEMAGH_EAR_WH": {605};
case "TRYK_SHEMAGH_ESS_G": {90};
case "TRYK_SHEMAGH_ESS": {90};
case "TRYK_SHEMAGH_ESS_WH": {90};
case "TRYK_SHEMAGH_SHADE_MH": {40};
case "TRYK_SHEMAGH_SHADE_G": {40};
case "TRYK_SHEMAGH_SHADE": {40};
case "TRYK_SHEMAGH_SHADE_WH": {40};
case "TRYK_SPSETG_GLASSES": {-1};
case "TRYK_SPGEAT_GLASSES": {-1};
case "TRYK_SPSET_PHC1_GLASSES": {-1};
case "TRYK_SPSET_PHC2_GLASSES": {-1};
case "TRYK_TAC_EARMUFF_GS": {595};
case "TRYK_TAC_SET_BN": {595};
case "TRYK_NOMIC_TAC_EARMUFF_GS": {595};
case "TRYK_TAC_EARMUFF_SHADE_GS": {625};
case "TRYK_TAC_SET_MESH_2": {635};
case "TRYK_TAC_SET_OD_2": {635};
case "TRYK_TAC_SET_TAN_2": {635};
case "TRYK_TAC_SET_WH_2": {635};
case "TRYK_TAC_SET_MESH": {635};
case "TRYK_TAC_SET_OD": {635};
case "TRYK_TAC_SET_TAN": {635};
case "TRYK_TAC_SET_WH": {635};

case "G_AVIATOR": {170};
case "G_BANDANNA_AVIATOR": {180};
case "G_BANDANNA_SPORT": {110};
case "G_COMBAT": {80};
case "G_COMBAT_GOGGLES_TNA_F": {80};
case "G_LADY_BLUE": {7};
case "G_LOWPROFILE": {100};
case "G_SHADES_BLACK": {84};
case "G_SHADES_BLUE": {84};
case "G_SHADES_GREEN": {84};
case "G_SHADES_RED": {84};
case "G_SPECTACLES": {16};
case "G_SPECTACLES_TINTED": {20};
case "G_SPORT_RED": {65};
case "G_SPORT_BLACKYELLOW": {65};
case "G_SPORT_BLACKWHITE": {65};
case "G_SPORT_CHECKERED": {65};
case "G_SPORT_BLACKRED": {100};
case "G_SPORT_GREENBLACK": {65};
case "G_SQUARES_TINTED": {42};
case "G_SQUARES": {37};

case "G_BALACLAVA_TI_BLK_F": {60};
case "G_BALACLAVA_TI_G_BLK_F": {140};
case "G_BALACLAVA_TI_TNA_F": {60};
case "G_BALACLAVA_TI_G_TNA_F": {140};

case "G_BALACLAVA_BLK": {5};
case "G_BALACLAVA_COMBAT": {85};
case "G_BALACLAVA_LOWPROFILE": {105};
case "G_BALACLAVA_OLI": {5};
case "G_BANDANNA_BEAST": {10};
case "G_BANDANNA_BLK": {10};
case "G_BANDANNA_KHK": {10};
case "G_BANDANNA_OLI": {10};
case "G_BANDANNA_SHADES": {94};
case "G_BANDANNA_TAN": {10};

case "RHS_BALACLAVA": {8};
case "RHS_BALACLAVA1_OLIVE": {8};
case "RHS_GOOGLES_BLACK": {30};
case "RHS_GOOGLES_YELLOW": {30};
case "RHS_GOOGLES_ORANGE": {30};
case "RHS_GOOGLES_CLEAR": {30};
case "RHS_ESS_BLACK": {80};
case "RHS_SCARF": {10};
CASE "RHSUSF_SHEMAGH_GRN": {10};
CASE "RHSUSF_SHEMAGH2_GRN": {10};
CASE "RHSUSF_SHEMAGH_OD": {10};
CASE "RHSUSF_SHEMAGH2_OD": {10};
CASE "RHSUSF_SHEMAGH_TAN": {10};
CASE "RHSUSF_SHEMAGH2_TAN": {10};
CASE "RHSUSF_SHEMAGH_WHITE": {10};
CASE "RHSUSF_SHEMAGH2_WHITE": {10};

CASE "RHSUSF_SHEMAGH_GOGG_GRN": {210};
CASE "RHSUSF_SHEMAGH2_GOGG_GRN": {210};
CASE "RHSUSF_SHEMAGH_GOGG_OD": {210};
CASE "RHSUSF_SHEMAGH2_GOGG_OD": {210};
CASE "RHSUSF_SHEMAGH_GOGG_TAN": {210};
CASE "RHSUSF_SHEMAGH2_GOGG_TAN": {210};
CASE "RHSUSF_SHEMAGH_GOGG_WHITE": {210};
CASE "RHSUSF_SHEMAGH2_GOGG_WHITE": {210};

CASE "RHSUSF_OAKLEY_GOGGLES_BLK": {200};
CASE "RHSUSF_OAKLEY_GOGGLES_CLR": {200};
CASE "RHSUSF_OAKLEY_GOGGLES_YLW": {200};

CASE "CUP_RUS_BALACLAVA_BLK": {8};
CASE "CUP_RUS_BALACLAVA_GRN": {8};
CASE "CUP_G_ESS_BLK_DARK": {80};
CASE "CUP_G_ESS_BLK_EMBER": {80};
CASE "CUP_G_ESS_BLK": {80};
CASE "CUP_G_ESS_CBR_DARK": {80};
CASE "CUP_G_ESS_CBR_EMBER": {80};
CASE "CUP_G_ESS_CBR": {80};
CASE "CUP_G_ESS_RGR_DARK": {80};
CASE "CUP_G_ESS_RGR_EMBER": {80};
CASE "CUP_G_ESS_RGR": {80};
CASE "CUP_G_ESS_KHK_DARK": {80};
CASE "CUP_G_ESS_KHK_EMBER": {80};
CASE "CUP_G_ESS_KHK": {80};

CASE "CUP_G_ESS_BLK_FACEWRAP_BLACK": {90};
CASE "CUP_G_ESS_RGR_FACEWRAP_RANGER": {90};
CASE "CUP_G_ESS_CBR_FACEWRAP_RED": {90};
CASE "CUP_G_ESS_RGR_FACEWRAP_SKULL": {90};
CASE "CUP_G_ESS_KHK_FACEWRAP_TAN": {90};
CASE "CUP_G_ESS_RGR_FACEWRAP_TROPICAL": {90};
CASE "CUP_G_ESS_KHK_FACEWRAP_WHITE": {90};

CASE "CUP_G_ESS_BLK_FACEWRAP_BLACK_GPS": {235};

CASE "CUP_G_ESS_BLK_SCARF_BLK": {90};
CASE "CUP_G_ESS_BLK_SCARF_GRN": {90};
CASE "CUP_G_ESS_BLK_SCARF_RED": {90};
CASE "CUP_G_ESS_KHK_SCARF_TAN": {90};
CASE "CUP_G_ESS_BLK_SCARF_WHITE": {90};
CASE "CUP_G_ESS_BLK_SCARF_FACE_BLK": {90};
CASE "CUP_G_ESS_BLK_SCARF_FACE_GRN": {90};
CASE "CUP_G_ESS_BLK_SCARF_FACE_RED": {90};
CASE "CUP_G_ESS_KHK_SCARF_FACE_TAN": {90};
CASE "CUP_G_ESS_BLK_SCARF_FACE_WHITE": {90};

CASE "CUP_G_ESS_BLK_SCARF_GRN_GPS": {235};
CASE "CUP_G_ESS_KHK_SCARF_TAN_GPS": {235};
CASE "CUP_G_ESS_BLK_SCARF_WHITE_GPS": {235};
CASE "CUP_G_ESS_BLK_SCARF_FACE_GRN_GPS": {235};
CASE "CUP_G_ESS_KHK_SCARF_FACE_TAN_GPS": {235};
CASE "CUP_G_ESS_BLK_SCARF_FACE_WHITE_GPS": {235};

CASE "CUP_PMC_FACEWRAP_BLACK": {10};
CASE "CUP_G_PMC_FACEWRAP_BLACK_GLASSES_DARK_HEADSET": {280}; // 10 + 190 + 80
CASE "CUP_G_PMC_FACEWRAP_BLACK_GLASSES_DARK": {200};
CASE "CUP_G_PMC_FACEWRAP_BLACK_GLASSES_EMBER": {200};

CASE "CUP_PMC_FACEWRAP_RANGER": {10};
CASE "CUP_PMC_FACEWRAP_RED": {10};
CASE "CUP_PMC_FACEWRAP_SKULL": {10};
CASE "CUP_PMC_FACEWRAP_SMILIE": {10};

CASE "CUP_PMC_FACEWRAP_TAN": {10};
CASE "CUP_G_PMC_FACEWRAP_TAN_GLASSES_DARK_HEADSET": {280};
CASE "CUP_G_PMC_FACEWRAP_TAN_GLASSES_DARK": {200};
CASE "CUP_G_PMC_FACEWRAP_TAN_GLASSES_EMBER": {200};

CASE "CUP_PMC_FACEWRAP_TROPICAL": {10};
CASE "CUP_G_PMC_FACEWRAP_TROPICAL_GLASSES_DARK_HEADSET": {280};
CASE "CUP_G_PMC_FACEWRAP_TROPICAL_GLASSES_DARK": {200};
CASE "CUP_G_PMC_FACEWRAP_TROPICAL_GLASSES_EMBER": {200};

CASE "CUP_PMC_FACEWRAP_WINTER": {10};
CASE "CUP_G_PMC_FACEWRAP_WINTER_GLASSES_DARK_HEADSET": {280};
CASE "CUP_G_PMC_FACEWRAP_WINTER_GLASSES_DARK": {200};
CASE "CUP_G_PMC_FACEWRAP_WINTER_GLASSES_EMBER": {200};

CASE "CUP_G_GPS": {145};
CASE "CUP_G_GRN_SCARF_SHADES_GPS": {345};
CASE "CUP_G_TAN_SCARF_SHADES_GPS": {345};
CASE "CUP_G_WHITE_SCARF_SHADES_GPS": {345};

CASE "CUP_G_PMC_RADIOHEADSET": {80};
CASE "CUP_G_PMC_RADIOHEADSET_GLASSES": {270};
CASE "CUP_G_PMC_RADIOHEADSET_GLASSES_DARK": {270};
CASE "CUP_G_PMC_RADIOHEADSET_GLASSES_EMBER": {270};

CASE "CUP_TK_NECKSCARF": {10};
CASE "CUP_G_SCARF_FACE_BLK": {10};
CASE "CUP_G_SCARF_FACE_GRN": {10};
CASE "CUP_G_SCARF_FACE_RED": {10};
CASE "CUP_G_SCARF_FACE_TAN": {10};
CASE "CUP_G_SCARF_FACE_WHITE": {10};

CASE "CUP_G_OAKLEYS_CLR": {190};
CASE "CUP_G_OAKLEYS_DRK": {190};
CASE "CUP_G_OAKLEYS_EMBR": {190};

CASE "CUP_G_TK_ROUNDGLASSES": {20};
CASE "CUP_G_TK_ROUNDGLASSES_BLK": {25};
CASE "CUP_G_TK_ROUNDGLASSES_GOLD": {90};

CASE "CUP_G_GRN_SCARF_SHADES": {200};
CASE "CUP_G_TAN_SCARF_SHADES": {200};
CASE "CUP_G_WHITE_SCARF_SHADES": {200};

CASE "CUP_FR_NECKSCARF3": {10};
CASE "CUP_FR_NECKSCARF": {10};
CASE "CUP_FR_NECKSCARF2": {10};
CASE "CUP_FR_NECKSCARF5": {10};
CASE "CUP_FR_NECKSCARF4": {10};

CASE "CUP_G_WATCHGPSCOMBO": {345};
CASE "CUP_G_GRN_SCARF_GPS": {355};
CASE "CUP_G_TAN_SCARF_GPS": {355};
CASE "CUP_G_WHITE_SCARF_GPS": {355};

CASE "CUP_G_GRN_SCARF_SHADES_GPSCOMBO": {545};
CASE "CUP_G_TAN_SCARF_SHADES_GPSCOMBO": {545};
CASE "CUP_G_WHITE_SCARF_SHADES_GPSCOMBO": {545};

//cigs
case "EWK_CIGAR1": {14};
case "EWK_CIGAR2": {14};
case "IMMERSION_CIGS_CIGAR0": {14};
case "EWK_CIG1": {1};
case "EWK_GLASSES_CIG1": {1};
case "IMMERSION_POPS_POP0": {1};
case "EWK_SHEMAG_NB_CIG6": {1};
CASE "EWK_SHEMAG_GRE_CIG6": {1};
CASE "EWK_SHEMAG_TAN_CIG6": {1};
CASE "EWK_GLASSES_SHEMAG_NB_CIG6": {1};
CASE "EWK_GLASSES_SHEMAG_GRE_CIG6": {1};
CASE "EWK_GLASSES_SHEMAG_TAN_CIG6": {1};
CASE "EWK_SHEMAG_NB": {10};
CASE "EWK_SHEMAG_LULZ": {10};
CASE "EWK_SHEMAG_GRE": {10};
CASE "EWK_SHEMAG_TAN": {10};


//beards 
case "SFG_TAC_BEARDD": {0};
case "SFG_TAC_BEARDB": {0};
case "SFG_TAC_BEARDG": {0};
case "SFG_TAC_BEARDO": {0};

case "SFG_TAC_CHOPSD": {0};
case "SFG_TAC_CHOPSG": {0};
case "SFG_TAC_CHOPSB": {0};
case "SFG_TAC_CHOPSO": {0};
case "SFG_TAC_MOUSTACHED": {0};
case "SFG_TAC_MOUSTACHEG": {0};
case "SFG_TAC_MOUSTACHEB": {0};
case "SFG_TAC_MOUSTACHEO": {0};
case "SFG_TAC_CHINLESSBD": {0};
case "SFG_TAC_CHINLESSBG": {0};
case "SFG_TAC_CHINLESSBB": {0};
case "SFG_TAC_CHINLESSBO": {0};

case "SFG_TAC_SMALLBEARDD": {0};
case "SFG_TAC_SMALLBEARDB": {0};
case "SFG_TAC_SMALLBEARDG": {0};
case "SFG_TAC_SMALLBEARDO": {0};

// "TAC Vests"
CASE "TRYK_BEARD_BL": {0};
CASE "TRYK_BEARD_BK": {0};
CASE "TRYK_BEARD": {0};
CASE "TRYK_BEARD_BW": {0};
CASE "TRYK_BEARD_GR": {0};
CASE "TRYK_BEARD_BL2": {0};
CASE "TRYK_BEARD_BK2": {0};
CASE "TRYK_BEARD2": {0};
CASE "TRYK_BEARD_BW2": {0};
CASE "TRYK_BEARD_GR2": {0};
CASE "TRYK_BEARD_BL3": {0};
CASE "TRYK_BEARD_BK3": {0};
CASE "TRYK_BEARD3": {0};
CASE "TRYK_BEARD_BW3": {0};
CASE "TRYK_BEARD_GR3": {0};
CASE "TRYK_BEARD_BL4": {0};
CASE "TRYK_BEARD_BK4": {0};
CASE "TRYK_BEARD4": {0};
CASE "TRYK_BEARD_BW4": {0};
CASE "TRYK_BEARD_GR4": {0};
CASE "TRYK_SBEARD_BL": {0};
CASE "TRYK_SBEARD_BK": {0};
CASE "TRYK_SBEARD": {0};
CASE "TRYK_SBEARD_BW": {0};
CASE "TRYK_SBEARD_GR": {0};
CASE "TRYK_SBEARD_BL2": {0};
CASE "TRYK_SBEARD_BK2": {0};
CASE "TRYK_SBEARD2": {0};
CASE "TRYK_SBEARD_BW2": {0};
CASE "TRYK_SBEARD_GR2": {0};
CASE "TRYK_SBEARD_BL3": {0};
CASE "TRYK_SBEARD_BK3": {0};
CASE "TRYK_SBEARD3": {0};
CASE "TRYK_SBEARD_BW3": {0};
CASE "TRYK_SBEARD_GR3": {0};
CASE "TRYK_SBEARD_BL4": {0};
CASE "TRYK_SBEARD_BK4": {0};
CASE "TRYK_SBEARD4": {0};
CASE "TRYK_SBEARD_BW4": {0};
CASE "TRYK_SBEARD_GR4": {0};
CASE "TRYK_SBEARD_BL5": {0};
CASE "TRYK_SBEARD_BK5": {0};
CASE "TRYK_SBEARD5": {0};
CASE "TRYK_SBEARD_BW5": {0};
CASE "TRYK_SBEARD_GR5": {0};
CASE "TRYK_SBEARD_BL6": {0};
CASE "TRYK_SBEARD_BK6": {0};
CASE "TRYK_SBEARD6": {0};
CASE "TRYK_SBEARD_BW6": {0};
CASE "TRYK_SBEARD_GR6": {0};



//NVGs

case "SAN_HEADLAMP_V2" : {25};
/*
case "RHS_1PN138": {1500};
case "RHSUSF_ANPVS_14": {3595};
case "RHSUSF_ANPVS_15": {12352};
case "RHSUSF_RHINO" : {178};
*/

// NVG-slot items (no actual NV capability)
// auto-generated code -- DO NOT TOUCH until next section!

case "SFG_TAC_BEARDD_NV" : {0};
case "SFG_TAC_BEARDB_NV" : {0};
case "SFG_TAC_BEARDG_NV" : {0};
case "SFG_TAC_BEARDO_NV" : {0};
case "SFG_TAC_CHOPSD_NV" : {0};
case "SFG_TAC_CHOPSG_NV" : {0};
case "SFG_TAC_CHOPSB_NV" : {0};
case "SFG_TAC_CHOPSO_NV" : {0};
case "SFG_TAC_MOUSTACHED_NV" : {0};
case "SFG_TAC_MOUSTACHEG_NV" : {0};
case "SFG_TAC_MOUSTACHEB_NV" : {0};
case "SFG_TAC_MOUSTACHEO_NV" : {0};
case "SFG_TAC_CHINLESSBD_NV" : {0};
case "SFG_TAC_CHINLESSBG_NV" : {0};
case "SFG_TAC_CHINLESSBB_NV" : {0};
case "SFG_TAC_CHINLESSBO_NV" : {0};
case "SFG_TAC_SMALLBEARDD_NV" : {0};
case "SFG_TAC_SMALLBEARDB_NV" : {0};
case "SFG_TAC_SMALLBEARDG_NV" : {0};
case "SFG_TAC_SMALLBEARDO_NV" : {0};
case "TRYK_US_ESS_GLASSES_NV" : {80};
case "TRYK_US_ESS_GLASSES_WH_NV" : {80};
case "TRYK_US_ESS_GLASSES_BLK_NV" : {80};
case "TRYK_US_ESS_GLASSES_TAN_NV" : {80};
case "TRYK_US_ESS_GLASSES_TAN_BLK_NV" : {80};
case "TRYK_HEADSET_GLASSES_NV" : {25};
case "EWK_GLASSES_SHEMAG_TAN_CIG6_NV" : {180};
case "EWK_GLASSES_SHEMAG_NB_CIG6_NV" : {180};
case "EWK_GLASSES_SHEMAG_GRE_CIG6_NV" : {180};
case "EWK_SHEMAG_TAN_CIG6_NV" : {10};
case "EWK_SHEMAG_NB_CIG6_NV" : {10};
case "EWK_SHEMAG_GRE_CIG6_NV" : {10};
case "EWK_SHEMAG_LULZ_NV" : {10};
case "EWK_SHEMAG_TAN_NV" : {10};
case "EWK_SHEMAG_NB_NV" : {10};
case "EWK_SHEMAG_GRE_NV" : {10};
case "TRYK_KIO_BALACLAVA_WH_NV" : {8};
case "TRYK_KIO_BALACLAVA_BLK_NV" : {8};
case "TRYK_KIO_BALACLAVAS_NV" : {8};
case "TRYK_KIO_BALACLAVA_BLK_EAR_NV" : {603};
case "TRYK_KIO_BALACLAVA_EAR_NV" : {603};
case "TRYK_KIO_BALACLAVA_ESS_NV" : {88};
case "TRYK_HEADSET2_GLASSES_NV" : {80};
case "TRYK_SHEMAGH_NV" : {10};
case "TRYK_SHEMAGH_MESH_NV" : {10};
case "TRYK_SHEMAGH_G_NV" : {10};
case "TRYK_SHEMAGH_WH_NV" : {10};
case "TRYK_SHEMAGH_SHADE_NV" : {40};
case "TRYK_SHEMAGH_SHADE_G_NV" : {40};
case "TRYK_SHEMAGH_SHADE_WH_NV" : {40};
case "TRYK_SHEMAGH_SHADE_MH_NV" : {40};
case "TRYK_SHEMAGH_ESS_NV" : {90};
case "TRYK_SHEMAGH_ESS_G_NV" : {90};
case "TRYK_SHEMAGH_ESS_WH_NV" : {90};
case "TRYK_SHEMAGH_EAR_TAN_NV" : {605};
case "TRYK_SHEMAGH_EAR_G_NV" : {605};
case "TRYK_SHEMAGH_EAR_WH_NV" : {605};
case "TRYK_TAC_EARMUFF_GS_NV" : {595};
case "TRYK_TAC_SET_BN_NV" : {595};
case "TRYK_NOMIC_TAC_EARMUFF_GS_NV" : {595};
case "TRYK_TAC_EARMUFF_SHADE_GS_NV" : {625};
case "TRYK_TAC_SET_TAN_NV" : {635};
case "TRYK_TAC_SET_OD_NV" : {635};
case "TRYK_TAC_SET_WH_NV" : {635};
case "TRYK_TAC_SET_MESH_NV" : {635};
case "TRYK_TAC_SET_TAN_2_NV" : {635};
case "TRYK_TAC_SET_OD_2_NV" : {635};
case "TRYK_TAC_SET_WH_2_NV" : {635};
case "TRYK_TAC_SET_MESH_2_NV" : {635};
case "G_SPECTACLES_NV" : {16};
case "G_SPECTACLES_TINTED_NV" : {20};
case "G_COMBAT_NV" : {80};
case "G_LOWPROFILE_NV" : {100};
case "G_SHADES_BLACK_NV" : {84};
case "G_SHADES_GREEN_NV" : {84};
case "G_SHADES_RED_NV" : {84};
case "G_SQUARES_NV" : {37};
case "G_SQUARES_TINTED_NV" : {42};
case "G_SPORT_BLACKWHITE_NV" : {65};
case "G_SPORT_BLACKYELLOW_NV" : {65};
case "G_SPORT_GREENBLACK_NV" : {65};
case "G_SPORT_CHECKERED_NV" : {65};
case "G_SPORT_RED_NV" : {65};
case "G_AVIATOR_NV" : {170};
case "G_LADY_BLUE_NV" : {7};
case "G_BALACLAVA_BLK_NV" : {5};
case "G_BALACLAVA_OLI_NV" : {5};
case "G_BALACLAVA_COMBAT_NV" : {85};
case "G_BALACLAVA_LOWPROFILE_NV" : {105};
case "G_BANDANNA_BLK_NV" : {10};
case "G_BANDANNA_OLI_NV" : {10};
case "G_BANDANNA_KHK_NV" : {10};
case "G_BANDANNA_TAN_NV" : {10};
case "G_BANDANNA_BEAST_NV" : {10};
case "G_BANDANNA_SHADES_NV" : {94};
case "G_BANDANNA_SPORT_NV" : {110};
case "G_BANDANNA_AVIATOR_NV" : {180};
case "G_SHADES_BLUE_NV" : {84};
case "G_SPORT_BLACKRED_NV" : {100};
case "TRYK_BEARD_NV" : {0};
case "TRYK_BEARD_BL_NV" : {0};
case "TRYK_BEARD_BW_NV" : {0};
case "TRYK_BEARD_BK_NV" : {0};
case "TRYK_BEARD_GR_NV" : {0};
case "TRYK_BEARD2_NV" : {0};
case "TRYK_BEARD_BL2_NV" : {0};
case "TRYK_BEARD_BW2_NV" : {0};
case "TRYK_BEARD_BK2_NV" : {0};
case "TRYK_BEARD_GR2_NV" : {0};
case "TRYK_BEARD3_NV" : {0};
case "TRYK_BEARD_BL3_NV" : {0};
case "TRYK_BEARD_BW3_NV" : {0};
case "TRYK_BEARD_BK3_NV" : {0};
case "TRYK_BEARD_GR3_NV" : {0};
case "TRYK_BEARD4_NV" : {0};
case "TRYK_BEARD_BL4_NV" : {0};
case "TRYK_BEARD_BW4_NV" : {0};
case "TRYK_BEARD_BK4_NV" : {0};
case "TRYK_BEARD_GR4_NV" : {0};
case "TRYK_SBEARD_NV" : {0};
case "TRYK_SBEARD_BL_NV" : {0};
case "TRYK_SBEARD_BW_NV" : {0};
case "TRYK_SBEARD_BK_NV" : {0};
case "TRYK_SBEARD_GR_NV" : {0};
case "TRYK_SBEARD2_NV" : {0};
case "TRYK_SBEARD_BL2_NV" : {0};
case "TRYK_SBEARD_BW2_NV" : {0};
case "TRYK_SBEARD_BK2_NV" : {0};
case "TRYK_SBEARD_GR2_NV" : {0};
case "TRYK_SBEARD3_NV" : {0};
case "TRYK_SBEARD_BL3_NV" : {0};
case "TRYK_SBEARD_BW3_NV" : {0};
case "TRYK_SBEARD_BK3_NV" : {0};
case "TRYK_SBEARD_GR3_NV" : {0};
case "TRYK_SBEARD4_NV" : {0};
case "TRYK_SBEARD_BL4_NV" : {0};
case "TRYK_SBEARD_BW4_NV" : {0};
case "TRYK_SBEARD_BK4_NV" : {0};
case "TRYK_SBEARD_GR4_NV" : {0};
case "TRYK_SBEARD5_NV" : {0};
case "TRYK_SBEARD_BL5_NV" : {0};
case "TRYK_SBEARD_BW5_NV" : {0};
case "TRYK_SBEARD_BK5_NV" : {0};
case "TRYK_SBEARD_GR5_NV" : {0};
case "TRYK_SBEARD6_NV" : {0};
case "TRYK_SBEARD_BL6_NV" : {0};
case "TRYK_SBEARD_BW6_NV" : {0};
case "TRYK_SBEARD_BK6_NV" : {0};
case "TRYK_SBEARD_GR6_NV" : {0};
case "G_BALACLAVA_TI_BLK_F_NV" : {60};
case "G_BALACLAVA_TI_TNA_F_NV" : {60};
case "G_BALACLAVA_TI_G_BLK_F_NV" : {140};
case "G_BALACLAVA_TI_G_TNA_F_NV" : {140};
case "G_COMBAT_GOGGLES_TNA_F_NV" : {80};
case "RHS_SCARF_NV" : {10};
case "RHS_BALACLAVA_NV" : {8};
case "RHS_BALACLAVA1_OLIVE_NV" : {8};
case "RHS_GOOGLES_BLACK_NV" : {30};
case "RHS_GOOGLES_CLEAR_NV" : {30};
case "RHS_GOOGLES_YELLOW_NV" : {30};
case "RHS_GOOGLES_ORANGE_NV" : {30};
case "RHS_ESS_BLACK_NV" : {80};
case "RHSUSF_OAKLEY_GOGGLES_BLK_NV" : {200};
case "RHSUSF_OAKLEY_GOGGLES_CLR_NV" : {200};
case "RHSUSF_OAKLEY_GOGGLES_YLW_NV" : {200};
case "RHSUSF_SHEMAGH_WHITE_NV" : {10};
case "RHSUSF_SHEMAGH_TAN_NV" : {10};
case "RHSUSF_SHEMAGH_OD_NV" : {10};
case "RHSUSF_SHEMAGH_GRN_NV" : {10};
case "RHSUSF_SHEMAGH_GOGG_WHITE_NV" : {210};
case "RHSUSF_SHEMAGH_GOGG_TAN_NV" : {210};
case "RHSUSF_SHEMAGH_GOGG_OD_NV" : {210};
case "RHSUSF_SHEMAGH_GOGG_GRN_NV" : {210};
case "RHSUSF_SHEMAGH2_WHITE_NV" : {10};
case "RHSUSF_SHEMAGH2_TAN_NV" : {10};
case "RHSUSF_SHEMAGH2_OD_NV" : {10};
case "RHSUSF_SHEMAGH2_GRN_NV" : {10};
case "RHSUSF_SHEMAGH2_GOGG_WHITE_NV" : {210};
case "RHSUSF_SHEMAGH2_GOGG_TAN_NV" : {210};
case "RHSUSF_SHEMAGH2_GOGG_OD_NV" : {210};
case "RHSUSF_SHEMAGH2_GOGG_GRN_NV" : {210};
case "CUP_PMC_FACEWRAP_BLACK_NV" : {10};
case "CUP_PMC_FACEWRAP_WINTER_NV" : {10};
case "CUP_PMC_FACEWRAP_TROPICAL_NV" : {10};
case "CUP_PMC_FACEWRAP_TAN_NV" : {10};
case "CUP_PMC_FACEWRAP_RED_NV" : {10};
case "CUP_PMC_FACEWRAP_RANGER_NV" : {10};
case "CUP_PMC_FACEWRAP_SMILIE_NV" : {10};
case "CUP_PMC_FACEWRAP_SKULL_NV" : {10};
case "CUP_G_PMC_FACEWRAP_BLACK_GLASSES_DARK_NV" : {200};
case "CUP_G_PMC_FACEWRAP_TAN_GLASSES_DARK_NV" : {200};
case "CUP_G_PMC_FACEWRAP_TROPICAL_GLASSES_DARK_NV" : {200};
case "CUP_G_PMC_FACEWRAP_WINTER_GLASSES_DARK_NV" : {200};
case "CUP_G_PMC_FACEWRAP_BLACK_GLASSES_EMBER_NV" : {200};
case "CUP_G_PMC_FACEWRAP_TAN_GLASSES_EMBER_NV" : {200};
case "CUP_G_PMC_FACEWRAP_TROPICAL_GLASSES_EMBER_NV" : {200};
case "CUP_G_PMC_FACEWRAP_WINTER_GLASSES_EMBER_NV" : {200};
case "CUP_G_PMC_FACEWRAP_BLACK_GLASSES_DARK_HEADSET_NV" : {280};
case "CUP_G_PMC_FACEWRAP_TAN_GLASSES_DARK_HEADSET_NV" : {280};
case "CUP_G_PMC_FACEWRAP_TROPICAL_GLASSES_DARK_HEADSET_NV" : {280};
case "CUP_G_PMC_FACEWRAP_WINTER_GLASSES_DARK_HEADSET_NV" : {280};
case "CUP_G_PMC_RADIOHEADSET_NV" : {80};
case "CUP_G_PMC_RADIOHEADSET_GLASSES_NV" : {270};
case "CUP_G_PMC_RADIOHEADSET_GLASSES_DARK_NV" : {270};
case "CUP_G_PMC_RADIOHEADSET_GLASSES_EMBER_NV" : {270};
case "CUP_RUS_BALACLAVA_BLK_NV" : {8};
case "CUP_RUS_BALACLAVA_GRN_NV" : {8};
case "CUP_TK_NECKSCARF_NV" : {10};
case "CUP_G_WRISTWATCH_NV" : {100};
case "CUP_G_GPS_NV" : {145};
case "CUP_G_WATCHGPSCOMBO_NV" : {345};
case "CUP_G_SCARF_FACE_WHITE_NV" : {10};
case "CUP_G_SCARF_FACE_BLK_NV" : {10};
case "CUP_G_SCARF_FACE_GRN_NV" : {10};
case "CUP_G_SCARF_FACE_TAN_NV" : {10};
case "CUP_G_SCARF_FACE_RED_NV" : {10};
case "CUP_G_GRN_SCARF_SHADES_GPSCOMBO_NV" : {545};
case "CUP_G_TAN_SCARF_SHADES_GPSCOMBO_NV" : {545};
case "CUP_G_WHITE_SCARF_SHADES_GPSCOMBO_NV" : {545};
case "CUP_G_GRN_SCARF_SHADES_GPS_NV" : {345};
case "CUP_G_TAN_SCARF_SHADES_GPS_NV" : {345};
case "CUP_G_WHITE_SCARF_SHADES_GPS_NV" : {345};
case "CUP_G_GRN_SCARF_SHADES_NV" : {200};
case "CUP_G_TAN_SCARF_SHADES_NV" : {200};
case "CUP_G_WHITE_SCARF_SHADES_NV" : {200};
case "CUP_G_GRN_SCARF_GPS_NV" : {355};
case "CUP_G_TAN_SCARF_GPS_NV" : {355};
case "CUP_G_WHITE_SCARF_GPS_NV" : {355};
case "CUP_G_ESS_KHK_DARK_NV" : {80};
case "CUP_G_ESS_KHK_EMBER_NV" : {80};
case "CUP_G_ESS_KHK_NV" : {80};
case "CUP_G_ESS_CBR_EMBER_NV" : {80};
case "CUP_G_ESS_CBR_DARK_NV" : {80};
case "CUP_G_ESS_CBR_NV" : {80};
case "CUP_G_ESS_RGR_EMBER_NV" : {80};
case "CUP_G_ESS_RGR_DARK_NV" : {80};
case "CUP_G_ESS_RGR_NV" : {80};
case "CUP_G_ESS_BLK_EMBER_NV" : {80};
case "CUP_G_ESS_BLK_DARK_NV" : {80};
case "CUP_G_ESS_BLK_NV" : {80};
case "CUP_G_ESS_BLK_SCARF_GRN_NV" : {90};
case "CUP_G_ESS_BLK_SCARF_BLK_NV" : {90};
case "CUP_G_ESS_BLK_SCARF_WHITE_NV" : {90};
case "CUP_G_ESS_KHK_SCARF_TAN_NV" : {90};
case "CUP_G_ESS_BLK_SCARF_RED_NV" : {90};
case "CUP_G_ESS_BLK_SCARF_WHITE_GPS_NV" : {235};
case "CUP_G_ESS_KHK_SCARF_TAN_GPS_NV" : {235};
case "CUP_G_ESS_BLK_SCARF_GRN_GPS_NV" : {235};
case "CUP_G_ESS_KHK_SCARF_FACE_TAN_NV" : {90};
case "CUP_G_ESS_BLK_SCARF_FACE_BLK_NV" : {90};
case "CUP_G_ESS_BLK_SCARF_FACE_GRN_NV" : {90};
case "CUP_G_ESS_BLK_SCARF_FACE_RED_NV" : {90};
case "CUP_G_ESS_BLK_SCARF_FACE_WHITE_NV" : {90};
case "CUP_G_ESS_KHK_SCARF_FACE_TAN_GPS_NV" : {235};
case "CUP_G_ESS_BLK_SCARF_FACE_WHITE_GPS_NV" : {235};
case "CUP_G_ESS_BLK_SCARF_FACE_GRN_GPS_NV" : {235};
case "CUP_G_ESS_BLK_FACEWRAP_BLACK_NV" : {90};
case "CUP_G_ESS_KHK_FACEWRAP_TAN_NV" : {90};
case "CUP_G_ESS_RGR_FACEWRAP_RANGER_NV" : {90};
case "CUP_G_ESS_KHK_FACEWRAP_WHITE_NV" : {90};
case "CUP_G_ESS_CBR_FACEWRAP_RED_NV" : {90};
case "CUP_G_ESS_RGR_FACEWRAP_SKULL_NV" : {90};
case "CUP_G_ESS_RGR_FACEWRAP_TROPICAL_NV" : {90};
case "CUP_G_ESS_BLK_FACEWRAP_BLACK_GPS_NV" : {235};
case "CUP_FR_NECKSCARF_NV" : {10};
case "CUP_FR_NECKSCARF2_NV" : {10};
case "CUP_FR_NECKSCARF3_NV" : {10};
case "CUP_FR_NECKSCARF4_NV" : {10};
case "CUP_FR_NECKSCARF5_NV" : {10};
case "CUP_G_OAKLEYS_DRK_NV" : {190};
case "CUP_G_OAKLEYS_CLR_NV" : {190};
case "CUP_G_OAKLEYS_EMBR_NV" : {190};
case "CUP_G_TK_ROUNDGLASSES_NV" : {20};
case "CUP_G_TK_ROUNDGLASSES_BLK_NV" : {25};
case "CUP_G_TK_ROUNDGLASSES_GOLD_NV" : {90};

//COMMUNICATION
//case "ITEMRADIO": {110};
case  "ACRE_PRC117F": {3707*_relationsMultiplier};
case  "ACRE_PRC148": {7500*_relationsMultiplier};
//case  "ACRE_PRC152": {7000*_relationsMultiplier};
case  "ACRE_PRC343": {110*_relationsMultiplier};
case  "ACRE_PRC77": {325};
//case  "ACRE_SEM52SL": {1500*_relationsMultiplier};
//case  "ACRE_SEM70": {5000*_relationsMultiplier};


//NAVIGATION
case "ITEMCOMPASS": {100};
case  "ACE_MICRODAGR": {2200*_relationsMultiplier};
case  "ACE_DAGR": {1832*_relationsMultiplier};
case "ITEMMAP": {2000*_relationsMultiplier};
case  "ACE_MAPTOOLS": {45};

//MISC ELECTRONICS
case  "ACE_ATRAGMX": {2064};
case  "ACE_CELLPHONE": {50};
case  "ACE_DEADMANSWITCH": {5};
/*
case  "ACE_UAVBATTERY": {400};
case  "ACE_HUNTIR_MONITOR": {3600};
case  "ACE_IR_STROBE_ITEM": {200};
case  "ACE_M26_CLACKER": {50};
case  "ACE_CLACKER": {75};
case  "MINEDETECTOR": {10000};
*/
case  "ACE_KESTREL4500": {460};
case  "ACE_FLASHLIGHT_KSF1": {40};
case  "ACE_FLASHLIGHT_XL50": {45};
case  "ACE_FLASHLIGHT_MX991": {20};


// MISC TOOLS
case  "ACE_SPRAYPAINTGREEN": {4};
case  "ACE_CABLETIE": {0.10};
case  "ACE_CHEMLIGHT_SHIELD": {8.4};
case  "ACE_DEFUSALKIT": {100};
case  "ACE_EARPLUGS": {15};
case  "ACE_ENTRENCHINGTOOL": {38.25};
case  "ACE_SPRAYPAINTRED": {4};
case  "ACE_WIRECUTTER": {272.41};
case  "TOOLKIT": {100};
case  "ACE_SANDBAG_EMPTY": {4};
case  "ACE_SPOTTINGSCOPE": {503.79};
case  "ACE_TRIPOD": {782};
case  "ACE_RANGECARD": {5};
case  "ACE_RANGETABLE_82MM": {5};
case  "ACE_SPRAYPAINTBLACK": {4};
case  "ACE_SPRAYPAINTBLUE": {4};
//case "BC_TOWROPE" : {300};
case "ACE_ROPE3" : {150};
case "ACE_ROPE6" : {300};
case "ACE_ROPE12" : {600};
case "ACE_ROPE15" : {750};
case "ACE_ROPE18" : {900};
case "ACE_ROPE27" : {1350};
case "ACE_ROPE36" : {1800};


//WATCH
case "ACE_ALTIMETER": {170};
case "ITEMWATCH": {100};
case "CUP_G_WRISTWATCH": {100}; //this one's actually a visible "facewear" item


// MEDICAL
case  "ACE_ADENOSINE": {59};
case  "ACE_SPLINT": {13};
case  "ACE_BANANA": {0.59};
case  "ACE_FIELDDRESSING": {2};
case  "ACE_ELASTICBANDAGE": {7};
case  "ACE_QUIKCLOT": {20};
case  "ACE_BLOODIV": {420};
case  "ACE_BLOODIV_250": {105};
case  "ACE_BLOODIV_500": {210};
case  "ACE_BODYBAG": {40};
case  "ACE_EPINEPHRINE": {55};
case  "ACE_MORPHINE": {25};
case  "ACE_PACKINGBANDAGE": {10};
case  "ACE_PERSONALAIDKIT": {25};
case  "ACE_PLASMAIV": {120};
case  "ACE_PLASMAIV_250": {30};
case  "ACE_PLASMAIV_500": {60};
case  "ACE_SALINEIV": {8};
case  "ACE_SALINEIV_250": {4.5};
case  "ACE_SALINEIV_500": {6};
case  "ACE_SURGICALKIT": {25};
case  "ACE_TOURNIQUET": {30};


// FOOD/DRINK
case  "ACE_CAN_FRANTA": {0.5};
case  "ACE_CAN_REDGULL": {1.5};
case  "ACE_CAN_SPIRIT": {0.5};
case  "ACE_CANTEEN_EMPTY": {12};
case  "ACE_MRE_BEEFSTEW": {8};
case  "ACE_MRE_CHICKENTIKKAMASALA": {8};
case  "ACE_MRE_CHICKENHERBDUMPLINGS": {8};
case  "ACE_MRE_CREAMCHICKENSOUP": {8};
case  "ACE_MRE_CREAMTOMATOSOUP": {8};
case  "ACE_MRE_LAMBCURRY": {8};
case  "ACE_MRE_MEATBALLSPASTA": {8};
case  "ACE_MRE_STEAKVEGETABLES": {8};
case  "ACE_WATERBOTTLE": {0.75};
case  "ACE_SUNFLOWER_SEEDS": {3};

default {-1};

};

_return
