R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
	"cargo_base_f",
	"land_cargobox_v1_f"
];

// TODO: update in line with numbers overhaul!
R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	["cargo_base_f", 170],
	["land_cargobox_v1_f", 14],
	[ "Land_Cargo10_sand_F", 250],
[ "Land_Cargo10_military_green_F", 250],
[ "Land_Cargo10_grey_F", 250],
[ "Land_Cargo20_sand_F", 500], 
[ "Land_Cargo20_military_green_F", 500],
[ "Land_Cargo20_grey_F", 500],
[ "Land_Cargo40_grey_F", 1000],
[ "Land_Cargo40_sand_F", 1000],
[ "Land_Cargo40_military_green_F", 1000]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
  ["Land_SandbagBarricade_01_half_F",5],
  ["Land_SandbagBarricade_01_hole_F",7],
	["targetbase", 3],
	["land_pierladder_f", 3],
	["metal_pole_f", 1],
	["land_canisterfuel_f", 2],
	["arrowmarker_r_f", 1],
	["land_pallet_f", 2],
	["land_pallets_stack_f", 4],
	["land_chairplastic_f", 1],
	["land_chairwood_f", 1],
	["items_base_f", 10],
	["land_metalbarrel_f", 5],
	["land_portable_generator_f", 6],
	["land_waterbarrel_f", 15],
	["land_watertank_f", 20],
	["land_campingchair_v1_f", 1],
	["land_campingchair_v2_f", 1],
	["land_campingtable_f", 2],
	["land_campingtable_small_f", 1],
	["land_camping_light_off_f", 1],
	["land_cargobox_v1_f", 15],
	["land_fieldtoilet_f", 4],
	["land_ground_sheet_folded_f", 1],
	["land_mapboard_f", 3],
	["land_plasticbarrier_03_f", 2],
	["land_redwhitepole_f", 1],
	["land_sink_f", 5],
	["land_sleeping_bag_folded_f", 1],
	["land_toiletbox_f", 4],
	["land_woodentable_large_f", 3],
	["land_woodentable_small_f", 2],
	["pole_f", 1],
	["roadcone_f", 1],
	[ "Land_PaperBox_01_open_boxes_F", 70],
	[ "Land_PaperBox_01_open_water_F", 70],
	[ "Land_FoodSacks_01_large_white_idap_F", 60],
	[ "Land_PlasticCase_01_large_idap_F", 30],
	[ "ACE_SandbagObject", 1],
	[ "Land_Camping_Light_F", 1],
	[ "Land_PortableHelipadLight_01_F", 1],
	[ "PortableHelipadLight_01_red_F", 1],
	[ "PortableHelipadLight_01_yellow_F", 1],
	[ "PortableHelipadLight_01_white_F", 1],
	[ "PortableHelipadLight_01_green_F", 1],
	[ "PortableHelipadLight_01_blue_F", 1],
	[ "RoadCone_F", 2],
	[ "RoadCone_L_F", 2],
	[ "Land_RoadCone_01_F", 3],
	[ "ACE_ConcertinaWireCoil", 5],
	[ "Land_Campfire_F", 15],
	[ "Land_Water_pipe_EP1", 4],
	[ "PlasticBarrier_03_orange_F", 20],
	[ "Land_Sign_WarningNoWeapon_F", 18],
	[ "Land_Sign_MinesDanger_English_F", 12],
	[ "Land_Sign_MinesTall_English_F", 5],
	[ "Land_Sign_MinesTall_F", 5],
	[ "Land_Sign_Mines_F", 2],
	[ "Sign_1L_Noentry_EP1", 5],
	[ "Sign_1L_Firstaid_EP1", 5],
	[ "Land_SignM_WarningMilitaryVehicles_english_F", 12],
	[ "Land_SignM_WarningMilAreaSmall_english_F", 12],
	[ "Sign_Checkpoint_TK_EP1", 9],
	[ "Sign_Danger", 9],
	[ "Sign_DangerMines_ACR", 5],
	[ "Land_WoodPile_F", 24],
	[ "FlagSmall_F", 4],
	[ "FlagMarker_01_F", 4],
	[ "ArrowDesk_L_F", 8],
	[ "ArrowDesk_R_F", 8],
	[ "Hedgehog", 20],
	[ "Land_CncBarrier_F", 40],
	[ "Land_CncBarrier_stripes_F", 40],
	[ "Land_CncBarrierMedium_F", 80],
	[ "Land_CncBarrierMedium4_F", 320],
	[ "Land_BarGate_F", 90],
	[ "Land_Rampart_F", 280],
	[ "SignAd_SponsorS_ION_F", 12],
	[ "Banner_01_F", 7],
	[ "SignAd_Sponsor_ION_F", 18],
	[ "Land_PortableLight_single_F", 10],
	[ "Land_PortableLight_double_F", 13],
	[ "Land_FieldToilet_F", 60],
	[ "Flag_US_F", 40],
	[ "CUP_FlagCarrierIONblack_PMC", 40],
	[ "Land_RedWhitePole_F", 10],
	[ "TapeSign_F", 4],
	[ "Hhedgehog_concreteBig", 180],
	[ "Hhedgehog_concrete", 130],
	[ "Land_ladder_half_EP1", 50],
	[ "Land_ladderEP1", 85],
	[ "Land_Hlaska", 250],
	[ "Land_Ind_IlluminantTower", 450],
	[ "Land_BagFence_End_F", 8],	
	[ "Land_BagFence_Short_F", 25],
	[ "Land_BagFence_Corner_F", 25],
	[ "Land_BagFence_Long_F", 50],
	[ "Land_BagFence_Round_F", 50],
	[ "Land_HBarrier_1_F", 60],
	[ "US_WarfareBBarrier5x_EP1", 300],
	[ "US_WarfareBBarrier10x_EP1", 600],
	[ "US_WarfareBBarrier10xTall_EP1", 1800],
	[ "Land_HBarrier_Big_F", 1200],
	[ "Land_HBarrier_3_F", 180],
	[ "Land_HBarrier_5_F", 300],
	[ "Land_HBarrierWall6_F", 1100],
	[ "Land_HBarrierWall_corner_F", 970],
	[ "Land_HBarrierWall4_F", 730],
	[ "Land_HBarrierTower_F", 1275],
	[ "Land_Fort_Watchtower_EP1", 789],
	[ "Land_BagBunker_Tower_F", 789],
	[ "Land_BagBunker_Small_F", 150],
	[ "Land_BagBunker_Large_F", 550],
	[ "Land_fort_artillery_nest_EP1", 520],
	[ "Land_fort_rampart_EP1", 200],
	[ "Fortress1", 150],
	[ "Fortress2", 350],
	[ "Land_HBarrierWall_corridor_F", 960],
	[ "CUP_USVehicleBox_EP1", 150],
	[ "WarfareBDepot", 1800],
	[ "Land_Cargo_Tower_V3_F", 5000],
	[ "Land_Cargo_Tower_V1_F", 5000],
	[ "Camp_EP1", 120],
	[ "CampEast", 200],
	[ "WarfareBCamp", 900],
	[ "US_WarfareBFieldhHospital_Base_EP1", 800],
	[ "MASH", 120],
	["ArrowMarker_L_F", 5],
	["ArrowMarker_R_F", 5],
	["RoadBarrier_F", 20],
	["RoadBarrier_small_F", 14],
	["CUP_A1_Road_ces_d6konec", 4],
	["CUP_A1_Road_ces_d6", 5],
	["CUP_A1_Road_ces_d12", 10],
	["CUP_A1_Road_ces_d25", 20]
	
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
	"ACE_Wheel",
  "Land_SandbagBarricade_01_half_F",
  "Land_SandbagBarricade_01_hole_F",
	"targetbase",
	"land_pierladder_f",
	"metal_pole_f",
	"arrowmarker_r_f",
	"land_pallet_f",
	"land_pallets_stack_f",
	"furniture_base_f",
	"items_base_f",
	"land_campingchair_v1_f",
	"land_campingchair_v2_f",
	"land_campingtable_f",
	"land_campingtable_small_f",
	"land_camping_light_off_f",
	"land_cargobox_v1_f",
	"land_fieldtoilet_f",
	"land_ground_sheet_folded_f",
	"land_mapboard_f",
	"land_plasticbarrier_03_f",
	"land_redwhitepole_f",
	"land_sink_f",
	"land_sleeping_bag_folded_f",
	"land_toiletbox_f",
	"land_woodentable_large_f",
	"land_woodentable_small_f",
	"pole_f",
	"roadcone_f",
	"WarfareBDepot",
	"Land_Cargo_Tower_V3_F",
	"Land_Cargo_Tower_V1_F",
	"Land_Hlaska",
	"Land_Fort_Watchtower_EP1",
	"Land_Ind_IlluminantTower",
	"Land_Rampart_F",
	"Banner_01_F",
	"FlagMarker_01_F",
	"ArrowDesk_L_F",
	"ArrowDesk_R_F",
	"ArrowMarker_L_F",
	"ArrowMarker_R_F",
	"RoadBarrier_F",
	"RoadBarrier_small_F",
	"Land_RoadCone_01_F",
	"RoadCone_L_F",
	"Land_RedWhitePole_F",
	"TapeSign_F",
	"Land_SignM_WarningMilAreaSmall_english_F",
	"Land_SignM_WarningMilitaryVehicles_english_F",
	"Land_Sign_MinesDanger_English_F",
	"Sign_Checkpoint_TK_EP1",
	"Sign_Danger",
	"Sign_1L_Firstaid_EP1",
	"Sign_DangerMines_ACR",
	"Sign_1L_Noentry_EP1",
	"Land_WoodPile_F",
	"Land_fort_rampart_EP1",
	"Land_Water_pipe_EP1",
	"Land_fort_artillery_nest_EP1",
	"ACE_SandbagObject",
	"PortableHelipadLight_01_red_F",
	"PortableHelipadLight_01_blue_F",
	"PortableHelipadLight_01_white_F",
	"PortableHelipadLight_01_green_F",
	"PortableHelipadLight_01_yellow_F",
	"Land_PortableHelipadLight_01_F",
	"Land_Cargo10_sand_F",
	"Land_Cargo10_military_green_F",
	"Land_Cargo10_grey_F",
	"Land_Cargo20_sand_F",
	"Land_Cargo20_military_green_F",
	"Land_Cargo20_grey_F",
	"Land_Cargo40_grey_F",
	"Land_Cargo40_sand_F",
	"Land_Cargo40_military_green_F",
	"Land_ladderEP1",
	"Land_ladder_half_EP1",
	"Hhedgehog_concrete",
	"Hhedgehog_concreteBig",
	"MASH",
	"Fortress1",
	"Fortress2",
	"Hedgehog",
	"Camp_EP1",
	"CampEast",
	"WarfareBCamp",
	"US_WarfareBFieldhHospital_Base_EP1",
	"CUP_A1_Road_ces_d6konec",
	"CUP_A1_Road_ces_d6",
	"CUP_A1_Road_ces_d12",
	"CUP_A1_Road_ces_d25"
];