// COMPONENT should be defined in the script_component.hpp and included BEFORE this hpp
#define PREFIX ace

#define MAJOR 1
#define MINOR 14
#define PATCHLVL 0
#define BUILD 597

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD


#define ACE_TAG A.C.E.
//text = QUOTE(A.C.E. Developer Version VERSION);
//text = QUOTE(A.C.E. Alpha VERSION);
//text = QUOTE(A.C.E. ReleaseCandidate VERSION);
//text = QUOTE(A.C.E. Final VERSION);


// MINIMAL required version for the Mod. Components can specify others..
#define REQUIRED_VERSION 1.62

/*
	#define DEBUG_ENABLED_SYS_ADDONS
	#define DEBUG_ENABLED_SYS_ATTACHMENTS
	#define DEBUG_ENABLED_SYS_BACKBLAST
	#define DEBUG_ENABLED_SYS_BLOOD
	#define DEBUG_ENABLED_SYS_CARTRIDGES
	#define DEBUG_ENABLED_SYS_CRATERS
	#define DEBUG_ENABLED_SYS_CREWPROTECTION
	#define DEBUG_ENABLED_SYS_DUMMIES
	#define DEBUG_ENABLED_SYS_EJECT
	#define DEBUG_ENABLED_SYS_EXPLOSIVES
	#define DEBUG_ENABLED_SYS_FLARES
	#define DEBUG_ENABLED_SYS_FLASHBANG
	#define DEBUG_ENABLED_SYS_GRENADETHROW
	#define DEBUG_ENABLED_SYS_HUNTIR
	#define DEBUG_ENABLED_SYS_INTERACTION
	#define DEBUG_ENABLED_SYS_IRSTROBE
	#define DEBUG_ENABLED_SYS_MULTI_BARREL
	#define DEBUG_ENABLED_SYS_MUZZLEBLAST
	#define DEBUG_ENABLED_SYS_NVG
	#define DEBUG_ENABLED_SYS_OVERHEATING
	#define DEBUG_ENABLED_SYS_RECOILDUST
	#define DEBUG_ENABLED_SYS_ROCKET_BALLISTICS
	#define DEBUG_ENABLED_SYS_SANDBAG
	#define DEBUG_ENABLED_SYS_SHOTGUN
	#define DEBUG_ENABLED_SYS_SIGHT_ADJUSTMENT_AT
	#define DEBUG_ENABLED_SYS_SIGHT_ADJUSTMENT_GL
	#define DEBUG_ENABLED_SYS_SIGHT_ADJUSTMENT_RIFLE
	#define DEBUG_ENABLED_SYS_SMAW_SPOTTINGRIFLE
	#define DEBUG_ENABLED_SYS_TRACERS
	#define DEBUG_ENABLED_SYS_TRACKING
	#define DEBUG_ENABLED_SYS_VIEWBLOCK
	#define DEBUG_ENABLED_SYS_VEHICLE
	#define DEBUG_ENABLED_SYS_VEHICLEDAMAGE
	#define DEBUG_ENABLED_SYS_WEAPONREST
	#define DEBUG_ENABLED_SYS_WOUNDS
*/
