mps_config_units = mps_config_units + [

["TKA","so","CUP_O_TK_SpecOps_MG",0],
["TKA","so","CUP_O_TK_SpecOps",0],
["TKA","so","CUP_O_TK_SpecOps_TL",0],
["TKA","at","CUP_O_TK_Soldier_HAT",2],
//["TKA","spc","CUP_O_TK_Soldier_AKS_Night",2],
//["TKA","spc","CUP_O_TK_Soldier_FNFAL_Night",2],
//["TKA","spc","CUP_O_TK_Soldier_AKS_74_GOSHAWK",2],
["TKA","cr","CUP_O_TK_Crew",0],
["TKA","pl","CUP_O_TK_Pilot",0],
["TKA","co","CUP_O_TK_Commander",0],
["TKA","sn","CUP_O_TK_Sniper",0], 
["TKA","sn","CUP_O_TK_Sniper_SVD_Night",0], 
["TKA","sn","CUP_O_TK_Sniper_KSVK",0], 
["TKA","aa","CUP_O_TK_Soldier_AA",2],
["TKA","at","CUP_O_TK_Soldier_AT",5],
["TKA","mg","CUP_O_TK_Soldier_AR",12],
["TKA","mg","CUP_O_TK_Soldier_MG",6],
["TKA","rf","CUP_O_TK_Soldier_AAT",25],
["TKA","rf","CUP_O_TK_Soldier_AMG",25],
["TKA","rf","CUP_O_TK_Soldier",50],
["TKA","rf","Hz_CUP_O_TK_Soldier2",25],
["TKA","rf","CUP_O_TK_Soldier_Backpack",25],
["TKA","med","CUP_O_TK_Medic",12],
["TKA","gl","CUP_O_TK_Soldier_GL",6],
["TKA","gl","Hz_CUP_O_TK_Soldier_GL2",6],
["TKA","at","CUP_O_TK_Soldier_LAT",12],
["TKA","tl","CUP_O_TK_Soldier_SL",5],
["TKA","dmr","Hz_CUP_O_TK_Soldier_DMR",6],

["INS","at","CUP_O_TK_INS_Soldier_AT",10],
//["INS","aa","CUP_O_TK_INS_Soldier_AA",2], //Strela
["INS","mg","CUP_O_TK_INS_Soldier_AR",10],
["INS","mg","CUP_O_TK_INS_Soldier_AR_RPK_Hz",10],
["INS","med","CUP_O_TK_INS_Guerilla_Medic",10],
["INS","mg","CUP_O_TK_INS_Soldier_MG",7],
["INS","gl","CUP_O_TK_INS_Soldier_GL",12],
["INS","rf","CUP_O_TK_INS_Soldier_AAT",2],
["INS","tl","CUP_O_TK_INS_Soldier_TL",2],
["INS","dmr","CUP_O_TK_INS_Sniper",3], //Mosin Sniper
["INS","co","CUP_O_TK_INS_Commander",0],
["INS","rf","CUP_O_TK_INS_Soldier",20],
["INS","rf","CUP_O_TK_INS_Soldier_Enfield",5],
["INS","rf","CUP_O_TK_INS_Soldier_K98_Hz",5],
["INS","rf","CUP_O_TK_INS_Soldier_Mosin_Hz",5],
["INS","rf","CUP_O_TK_INS_Soldier_SKS_Hz",5],
["INS","rf","CUP_O_TK_INS_Soldier_M1Garand_Hz",2],
["INS","rf","CUP_O_TK_INS_Soldier_MP44_Hz",1],
["INS","rf","CUP_O_TK_INS_Soldier_FNFAL",5],
["INS","at","CUP_I_TK_GUE_Soldier_AT",10],
["INS","rf","CUP_I_TK_GUE_Soldier_AAT",10],
["INS","med","CUP_I_TK_GUE_Guerilla_Medic",10],
["INS","med","CUP_I_TK_GUE_Guerilla_Medic2_Hz",2],
["INS","rf","CUP_I_TK_GUE_Guerilla_Enfield",7],
["INS","dmr","CUP_I_TK_GUE_Sniper",5], //SVD
["INS","mg","CUP_I_TK_GUE_Soldier_MG",7],
["INS","tl","CUP_I_TK_GUE_Soldier_TL",10],
["INS","co","CUP_I_TK_GUE_Commander",0],
//["INS","at","CUP_I_TK_GUE_Soldier_HAT",1], //Dragon
["INS","rf","CUP_I_TK_GUE_Soldier",100],
["INS","rf","CUP_I_TK_GUE_Soldier_AK_47S",10],
["INS","rf","LOP_AM_Infantry_Rifleman_9",1], //vz58
["INS","mg","CUP_I_TK_GUE_Soldier_AR",10],
["INS","mg","CUP_I_TK_GUE_Soldier_AR_DP_Hz",1],
//["INS","aa","CUP_I_TK_GUE_Soldier_AA",1], //Stinger
["INS","rf","CUP_I_TK_GUE_Soldier_M16A2",2],
["INS","gl","CUP_I_TK_GUE_Soldier_GL",1], //M16

["IA","tl","LOP_IA_Infantry_SL",5],
["IA","cr","LOP_IA_Infantry_Crewman",0],
["IA","med","LOP_IA_Infantry_Corpsman",12],
["IA","gl","LOP_IA_Infantry_GL",6],
["IA","at","LOP_IA_Infantry_AT",5],
["IA","at","LOP_IA_Infantry_Rifleman_2",12],
["IA","rf","LOP_IA_Infantry_AT_Asst",25],
["IA","rf","LOP_IA_Infantry_MG_Asst",25],
["IA","rf","LOP_IA_Infantry_Rifleman",25],
["IA","rf","LOP_IA_Infantry_Rifleman_4",50],
["IA","rf","LOP_IA_Infantry_Rifleman_3",25],
["IA","mg","LOP_IA_Infantry_MG",6],
["IA","dmr","LOP_IA_Infantry_Marksman",6],
["IA","rf","LOP_IA_Infantry_Rifleman_M16A2_Hz",3],
["IA","mg","LOP_IA_Infantry_AR_Hz",12],
["IA","rf","LOP_IA_Infantry_AR_Asst_Hz",25],
["IA","so","PO_IA_Infantry_SF_Operator",0],
["IA","so","PO_IA_Infantry_SF_GL",0],
["IA","so","PO_IA_Infantry_SF_TL",0],
["IA","so","PO_IA_Infantry_SF_Corpsman",0],
["IA","sn","PO_IA_Infantry_SF_Marksman",0]

];