mps_config_vehicles = mps_config_vehicles + [

	["TKA","attakp","CUP_O_Su25_TKA"],
	["TKA","attakp","rki_mig21naf_MR_fia"],
	["TKA","attakp","rki_mig21naf_LBMB_fiar"],
	["TKA","attakp","rki_mig21naf_HCAS_fia"],
	["TKA","attakp","rki_mig21naf_CAS_fia"],
	["TKA","attakp","rki_mig21naf_AGM_fia"],
	["TKA","attakp","CUP_O_L39_RKT_TK"],
	["TKA","Lbomber","rki_mig21naf_HBMB_fia"],
	["TKA","Lbomber","CUP_O_L39_BMB_TK"],
	["TKA","Lbomber","rki_mig21naf_EHCAS_fia"],
	["TKA","Lbomber","rki_mig21naf_BMB_fia"],
	["TKA","airsup","rki_mig21naf_CAP_fia"],	
	["TKA","airsup","Fox_MIG25_O_CAP"],	
	["TKA","airsup","CUP_O_L39_CAP_TK"],	
	["TKA","Hbomber","RHS_TU95MS_vvs_old"],	
	["TKA","attakh","LOP_TKA_Mi8MTV3_FAB"],
	["TKA","attakh","LOP_TKA_Mi24V_FAB"],
	["TKA","attakh","CUP_O_Mi24_D_TK"],
	["TKA","attakh","CUP_O_Mi8_SLA_2"],
	["TKA","cargoh", "CUP_O_Mi17_TK"],
	["TKA","cargoh", "CUP_O_UH1H_TKA"],
	["TKA","tank", "CUP_O_ZSU23_Afghan_TK"],	
	["TKA","tank", "rhs_t80"],
	//["TKA","tank", "rhs_t80b"],
	["TKA","tank", "LOP_TKA_T55"],
	["TKA","tank", "LOP_TKA_T72BA"],
	//["TKA","tank", "LOP_TKA_T72BB"],
	//["TKA","tank", "rhssaf_army_t72s"],	
	["TKA","tank", "CUP_O_T72_TKA"],
	["TKA","apc", "CUP_O_BRDM2_TKA"],
	["TKA","apc", "CUP_O_M113_TKA"],
	["TKA","apc", "LOP_TKA_BMP1"],
	["TKA","apc", "LOP_TKA_BMP2"],
	["TKA","apc", "LOP_TKA_BTR70"],
	["TKA","apc", "LOP_TKA_BTR60"],
	//["TKA","apc", "CUP_O_BMP1P_TKA"],
	//["TKA","apc", "LOP_TKA_BMP1D"],
	//["TKA","apc", "LOP_TKA_BMP2D"],
	//["TKA","mobiaa", "LOP_TKA_ZSU234"],
	//["TKA","mobiaa", "CUP_O_BMP2_ZU_TKA"],
	["TKA","mobiaa", "CUP_O_Ural_ZU23_TKA"],
	["TKA","tdest", "CUP_O_BRDM2_ATGM_TKA"],
	["TKA","tdest", "CUP_O_UAZ_METIS_TKA"],
	["TKA","truck", "LOP_TKA_Ural"],
	["TKA","truck", "LOP_TKA_Ural_open"],
	["TKA","truck", "CUP_O_V3S_Open_TKA"],
	["TKA","truck", "CUP_O_V3S_Covered_TKA"],
	["TKA","cargoc", "LOP_TKA_UAZ"],
	["TKA","cargoc", "LOP_TKA_UAZ_Open"],
	["TKA","cargoc", "CUP_O_LR_Transport_TKA"],
	["TKA","attakc", "LOP_TKA_UAZ_AGS"],
	["TKA","attakc", "LOP_TKA_UAZ_DshKM"],
	["TKA","attakc", "LOP_TKA_UAZ_SPG"],
	["TKA","attakc", "CUP_O_LR_MG_TKA"],
	["TKA","attakc", "CUP_O_LR_SPG9_TKA"],
	["TKA","static", "rhsgref_nat_Igla_AA_pod"],
	["TKA","static", "rhsgref_nat_AGS30_TriPod"],
	["TKA","static", "rhsgref_nat_DSHKM"],
	["TKA","static", "rhsgref_nat_DSHKM_Mini_TriPod"],
	["TKA","static", "rhsgref_nat_SPG9"],
	["TKA","static", "rhsgref_nat_NSV_TriPod"],
	["TKA","static", "rhsgref_nat_ZU23"],
	["TKA","static", "LOP_NAPA_Static_M2"],
	["TKA","static", "LOP_NAPA_Static_M2_MiniTripod"],
	["TKA","static", "LOP_TKA_Static_AT4"],
	["TKA","cargop", "CUP_B_C47_USA"],
	
	["INS","attakc","CUP_I_Datsun_PK_TK"],
	["INS","attakc","CUP_I_Datsun_PK_TK_Random"],
	["INS","attakc","LOP_AM_Offroad_M2"],
	["INS","attakc","LOP_AM_Landrover_SPG9"],
	["INS","attakc","LOP_AM_Landrover_M2"],
	["INS","cargoc","CUP_I_Datsun_4seat_TK"],
	["INS","truck","CUP_I_V3S_Open_TKG"],
	["INS","truck","CUP_I_V3S_Covered_TKG"],
	["INS","apc","CUP_I_BTR40_MG_TKG"],
	["INS","mobiaa","CUP_I_Ural_ZU23_TK_Gue"],
	["INS","tank","CUP_I_T34_TK_GUE"],
	
	["IA","attakh","LOP_IA_Mi24V_FAB"],
	["IA","attakh","LOP_IA_Mi8MTV3_FAB"],
	["IA","cargoh","LOP_IA_Mi8MT_Cargo"],
	["IA","cargoh","LOP_IA_UH1Y_UN"],
	["IA","cargop","RHS_C130J"],
	["IA","airsup","FIR_F16C_Ag_lizard"],
	["IA","attakp","rhsgref_cdf_b_su25"],
	["IA","cargoc","LOP_IA_M1025_D"],
	["IA","truck","LOP_IA_Ural"],
	["IA","truck","LOP_IA_Ural_open"],
	["IA","attakc","LOP_IA_M1025_W_M2"],
	["IA","attakc","LOP_IA_M1025_W_Mk19"],
	["IA","apc","LOP_IA_BMP1"],
	["IA","apc","LOP_IA_BTR80"],
	["IA","apc","LOP_IA_M113_W"],
	["IA","tank","LOP_IA_M1A1_AIM_D"],
	["IA","tank","LOP_IA_T55"],
	["IA","tank","LOP_IA_T72BA"],
	["IA","mobiaa","LOP_IA_ZSU234"]
        
];