mps_config_units = mps_config_units + [

["TKA","so","CUP_O_TK_SpecOps_MG",0],
["TKA","so","CUP_O_TK_SpecOps",0],
["TKA","so","CUP_O_TK_SpecOps_TL",0],
["TKA","at","CUP_O_TK_Soldier_HAT",2],
["TKA","spc","CUP_O_TK_Soldier_AKS_Night",2],
["TKA","spc","CUP_O_TK_Soldier_FNFAL_Night",2],
["TKA","spc","CUP_O_TK_Soldier_AKS_74_GOSHAWK",2],
["TKA","cr","CUP_O_TK_Crew",0],
["TKA","co","CUP_O_TK_Commander",0],
["TKA","sn","CUP_O_TK_Sniper",0], 
["TKA","sn","CUP_O_TK_Sniper_SVD_Night",0], 
["TKA","sn","CUP_O_TK_Sniper_KSVK",0], 
["TKA","aa","CUP_O_TK_Soldier_AA",2],
["TKA","at","CUP_O_TK_Soldier_AT",5],
["TKA","mg","CUP_O_TK_Soldier_AR",12],
["TKA","mg","CUP_O_TK_Soldier_MG",6],
["TKA","rf","CUP_O_TK_Soldier_AAT",25],
["TKA","rf","CUP_O_TK_Soldier_AMG",25],
["TKA","rf","CUP_O_TK_Soldier",50],
["TKA","rf","Hz_CUP_O_TK_Soldier2",25],
["TKA","rf","CUP_O_TK_Soldier_Backpack",25],
["TKA","med","CUP_O_TK_Medic",12],
["TKA","gl","CUP_O_TK_Soldier_GL",6],
["TKA","gl","Hz_CUP_O_TK_Soldier_GL2",6],
["TKA","at","CUP_O_TK_Soldier_LAT",12],
["TKA","tl","CUP_O_TK_Soldier_SL",5],
["TKA","dmr","Hz_CUP_O_TK_Soldier_DMR",6]

];