mps_config_units = mps_config_units + [
["BIS_US","aa","US_Soldier_AA_EP1"],
["BIS_US","at","US_Soldier_AT_EP1"],
["BIS_US","at","US_Soldier_AAT_EP1"],
["BIS_US","at","US_Soldier_HAT_EP1"],
["BIS_US","at","US_Soldier_AHAT_EP1"],
["BIS_US","mg","US_Soldier_AR_EP1"],
["BIS_US","mg","US_Soldier_AAR_EP1"],
["BIS_US","cr","US_Soldier_Crew_EP1"],
["BIS_US","en","US_Soldier_Engineer_EP1"],
["BIS_US","so","US_Soldier_GL_EP1"],
["BIS_US","mg","US_Soldier_MG_EP1"],
["BIS_US","mg","US_Soldier_AMG_EP1"],
["BIS_US","sn","US_Soldier_Marksman_EP1"],
["BIS_US","na","US_Soldier_Medic_EP1"],
["BIS_US","tl","US_Soldier_Officer_EP1"],
["BIS_US","pi","US_Soldier_Pilot_EP1"],
["BIS_US","na","US_Soldier_EP1"],
["BIS_US","at","US_Soldier_LAT_EP1"],
["BIS_US","na","US_Soldier_B_EP1"],
["BIS_US","sn","US_Soldier_Sniper_EP1"],
["BIS_US","sn","US_Soldier_SniperH_EP1"],
["BIS_US","sn","US_Soldier_Sniper_NV_EP1"],
["BIS_US","sn","US_Soldier_Spotter_EP1"],
["BIS_US","tl","US_Soldier_SL_EP1"],
["BIS_US","tl","US_Soldier_TL_EP1"],
["BIS_US","mg","US_Delta_Force_AR_EP1"],
["BIS_US","mg","US_Delta_Force_MG_EP1"],
["BIS_US","sn","US_Delta_Force_Marksman_EP1"],
["BIS_US","na","US_Delta_Force_Medic_EP1"],
["BIS_US","so","US_Delta_Force_EP1"],
["BIS_US","so","US_Delta_Force_Assault_EP1"],
["BIS_US","at","US_Delta_Force_M14_EP1"],
["BIS_US","so","US_Delta_Force_Night_EP1"],
["BIS_US","so","US_Delta_Force_SD_EP1"],
["BIS_US","tl","US_Delta_Force_TL_EP1"],

["BIS_CZ","mg","CZ_Soldier_AMG_DES_EP1"],
["BIS_CZ","mg","CZ_Soldier_MG_DES_EP1"],
["BIS_CZ","tl","CZ_Soldier_Office_DES_EP1"],
["BIS_CZ","pi","CZ_Soldier_Pilot_EP1"],
["BIS_CZ","na","CZ_Soldier_DES_EP1"],
["BIS_CZ","at","CZ_Soldier_AT_DES_EP1"],
["BIS_CZ","na","CZ_Soldier_B_DES_EP1"],
["BIS_CZ","sn","CZ_Soldier_Sniper_EP1"],
["BIS_CZ","tl","CZ_Soldier_SL_DES_EP1"],
["BIS_CZ","so","CZ_Special_Forces_GL_DES_EP1"],
["BIS_CZ","mg","CZ_Special_Forces_MG_DES_EP1"],
["BIS_CZ","so","CZ_Special_Forces_DES_EP1"],
["BIS_CZ","sn","CZ_Special_Forces_Scout_DES_EP1"],
["BIS_CZ","tl","CZ_Special_Forces_TL_DES_EP1"],

["BIS_GER","mg","GER_Soldier_MG_EP1"],
["BIS_GER","na","GER_Soldier_Medic_EP1"],
["BIS_GER","na","GER_Soldier_EP1"],
["BIS_GER","sn","GER_Soldier_Scout_EP1"],
["BIS_GER","tl","GER_Soldier_TL_EP1"],

["BIS_TK","aa","TK_Soldier_AA_EP1",2],
//["BIS_TK","at","TK_Soldier_AAT_EP1"],
//["BIS_TK","mg","TK_Soldier_AMG_EP1"],
["BIS_TK","at","TK_Soldier_HAT_EP1",5], //RPG-7
["BIS_TK","mg","TK_Soldier_AR_EP1",12],
["BIS_TK","co","TK_Commander_EP1",0],
["BIS_TK","cr","TK_Soldier_Crew_EP1",0],
["BIS_TK","en","TK_Soldier_Engineer_EP1",0],
["BIS_TK","gl","TK_Soldier_GL_EP1",6],
["BIS_TK","mg","TK_Soldier_MG_EP1",6],
["BIS_TK","med","TK_Soldier_Medic_EP1",12],
["BIS_TK","tl","TK_Soldier_Officer_EP1",1],
["BIS_TK","pi","TK_Soldier_Pilot_EP1",0],
["BIS_TK","rf","TK_Soldier_EP1",50],
["BIS_TK","rf","TK_Soldier_B_EP1",25],
["BIS_TK","at","TK_Soldier_LAT_EP1",12], //RPG-18
["BIS_TK","at","TK_Soldier_AT_EP1",2], //Metis
["BIS_TK","sn","TK_Soldier_Sniper_EP1",5], //SVD
//["BIS_TK","sn","TK_Soldier_SniperH_EP1"],
["BIS_TK","sn","TK_Soldier_Sniper_Night_EP1",2], //SVD NV
["BIS_TK","spc","TK_Soldier_Night_1_EP1",2], //AK-74 NV
["BIS_TK","spc","TK_Soldier_Night_2_EP1",2], //FN FAL NV
["BIS_TK","spc","TK_Soldier_TWS_EP1",1],
//["BIS_TK","sn","TK_Soldier_Spotter_EP1"],
["BIS_TK","tl","TK_Soldier_SL_EP1",5],
["BIS_TK","so","TK_Special_Forces_MG_EP1",0],
["BIS_TK","so","TK_Special_Forces_EP1",0],
["BIS_TK","so","TK_Special_Forces_TL_EP1",0],

["BIS_TK_INS","rf","ACE_TK_INS_Soldier_AKM_EP1",50], //requires ACE
["BIS_TK_INS","rf","TK_INS_Soldier_EP1",10], //AK-74
["BIS_TK_INS","gl","TK_INS_Soldier_2_EP1",2], //AK-74 GL
["BIS_TK_INS","rf","TK_INS_Soldier_3_EP1",5], //Lee Enf
["BIS_TK_INS","rf","TK_INS_Soldier_4_EP1",4], //FN FAL
["BIS_TK_INS","rf","TK_GUE_Soldier_2_EP1",4], //AKMS
["BIS_TK_INS","at","TK_GUE_Soldier_AT_EP1",5], 
["BIS_TK_INS","aa","TK_INS_Soldier_AA_EP1",1],
["BIS_TK_INS","mg","TK_INS_Soldier_AR_EP1",4],
//["BIS_TK_INS","at","TK_INS_Soldier_AT_EP1",5],
//["BIS_TK_INS","at","TK_INS_Soldier_AAT_EP1"],
["BIS_TK_INS","mg","TK_INS_Soldier_MG_EP1",2],
//["BIS_TK_INS","sn","TK_INS_Soldier_Sniper_EP1"], //AK-74 optics
["BIS_TK_INS","sn","TK_GUE_Soldier_Sniper_EP1",2],
//["BIS_TK_INS","tl","TK_INS_Soldier_TL_EP1"], //AK-74 GL
["BIS_TK_INS","spc","TK_INS_Bonesetter_EP1",1],
["BIS_TK_INS","tl","TK_INS_Warlord_EP1",5], //AKS-74u

["BIS_UNO","at","UN_CDF_Soldier_AAT_EP1"],
["BIS_UNO","mg","UN_CDF_Soldier_AMG_EP1"],
["BIS_UNO","cr","UN_CDF_Soldier_Crew_EP1"],
["BIS_UNO","na","UN_CDF_Soldier_Guard_EP1"],
["BIS_UNO","mg","UN_CDF_Soldier_MG_EP1"],
["BIS_UNO","tl","UN_CDF_Soldier_Officer_EP1"],
["BIS_UNO","pi","UN_CDF_Soldier_Pilot_EP1"],
["BIS_UNO","na","UN_CDF_Soldier_EP1"],
["BIS_UNO","na","UN_CDF_Soldier_B_EP1"],
["BIS_UNO","at","UN_CDF_Soldier_AT_EP1"],
["BIS_UNO","tl","UN_CDF_Soldier_SL_EP1"],

["BIS_TK_GUE","aa","TK_GUE_Soldier_AA_EP1"],
["BIS_TK_GUE","mg","TK_GUE_Soldier_AR_EP1"],
["BIS_TK_GUE","na","TK_GUE_Bonesetter_EP1"],
["BIS_TK_GUE","na","TK_GUE_Soldier_EP1"],
["BIS_TK_GUE","na","TK_GUE_Soldier_2_EP1"],
["BIS_TK_GUE","at","TK_GUE_Soldier_HAT_EP1"],
["BIS_TK_GUE","na","TK_GUE_Soldier_5_EP1"],
["BIS_TK_GUE","na","TK_GUE_Soldier_3_EP1"],
["BIS_TK_GUE","at","TK_GUE_Soldier_AAT_EP1"],
["BIS_TK_GUE","at","TK_GUE_Soldier_AT_EP1"],
["BIS_TK_GUE","sn","TK_GUE_Soldier_Sniper_EP1"],
["BIS_TK_GUE","mg","TK_GUE_Soldier_MG_EP1"],
["BIS_TK_GUE","tl","TK_GUE_Soldier_TL_EP1"],
["BIS_TK_GUE","tl","TK_GUE_Warlord_EP1"],

["ISIS_Terrorists","aa","MIS_ISIS_01_AA"],
["ISIS_Terrorists","aa","MIS_ISIS_02_AA"],  
["ISIS_Terrorists","aa","MIS_ISIS_03_AA"],  
["ISIS_Terrorists","aa","MIS_ISIS_04_AA"],  
["ISIS_Terrorists","mg","MIS_ISIS_02_MG"],
["ISIS_Terrorists","na","MIS_ISIS_02_Med"],
["ISIS_Terrorists","na","MIS_ISIS_01_Med"],
["ISIS_Terrorists","na","MIS_ISIS_03_Med"],
["ISIS_Terrorists","at","MIS_ISIS_01_AT"],
["ISIS_Terrorists","na","MIS_ISIS_01_Rif"],
["ISIS_Terrorists","na","MIS_ISIS_04_Med"],
["ISIS_Terrorists","na","MIS_ISIS_02_Rif"],
["ISIS_Terrorists","na","MIS_ISIS_03_Rif"],
["ISIS_Terrorists","na","MIS_ISIS_04_Rif"],
["ISIS_Terrorists","at","MIS_ISIS_02_AT"],
["ISIS_Terrorists","at","MIS_ISIS_03_AT"],
["ISIS_Terrorists","at","MIS_ISIS_03_AT"],
["ISIS_Terrorists","at","MIS_ISIS_04_AT"],
["ISIS_Terrorists","sn","MIS_ISIS_01_SVD"],
["ISIS_Terrorists","sn","MIS_ISIS_03_SVD"],
["ISIS_Terrorists","sn","MIS_ISIS_02_SVD"],
["ISIS_Terrorists","sn","MIS_ISIS_04_SVD"],
["ISIS_Terrorists","mg","MIS_ISIS_03_MG"],
["ISIS_Terrorists","mg","MIS_ISIS_04_MG"],
["ISIS_Terrorists","tl","MIS_ISIS_01_TWS"],
["ISIS_Terrorists","tl","MIS_ISIS_02_TWS"],
["ISIS_Terrorists","tl","MIS_ISIS_03_TWS"],
["ISIS_Terrorists","tl","MIS_ISIS_04_TWS"],
["ISIS_Terrorists","cr","MIS_ISIS_01_Engineer"],
["ISIS_Terrorists","cr","MIS_ISIS_02_Engineer"],
["ISIS_Terrorists","cr","MIS_ISIS_03_Engineer"],
["ISIS_Terrorists","cr","MIS_ISIS_04_Engineer"]


];