#define LIB_fnc_isTurnedOut					CBA_fnc_isTurnedOut
#define LIB_fnc_headDir						CBA_fnc_headDir
#define LIB_fnc_globalEvent					CBA_fnc_globalEvent
#define	LIB_fnc_hashCreate					CBA_fnc_hashCreate
#define	LIB_fnc_hashSet						CBA_fnc_hashSet
#define	LIB_fnc_hashGet						CBA_fnc_hashGet
#define LIB_fnc_readKeyFromConfig			CBA_fnc_readKeyFromConfig
#define	LIB_fnc_addEventHandler				CBA_fnc_addEventHandler
#define LIB_fnc_addKeyHandlerFromConfig		CBA_fnc_addKeyHandlerFromConfig
#define LIB_fnc_hashHasKey					CBA_fnc_hashHasKey
#define LIB_fnc_find						CBA_fnc_find
#define LIB_fnc_remoteEvent					CBA_fnc_remoteEvent
#define LIB_fnc_localEvent					CBA_fnc_localEvent
#define LIB_fnc_distance2D					BIS_fnc_distance2D
#define LIB_fnc_dirTo						BIS_fnc_dirTo
#define LIB_fnc_relPos						BIS_fnc_relPos
#define LIB_fnc_openPipe					jayarma2lib_fnc_openPipe
#define LIB_fnc_closePipe					jayarma2lib_fnc_closePipe
#define LIB_fnc_readPipe					jayarma2lib_fnc_readPipe
#define LIB_fnc_writePipe					jayarma2lib_fnc_writePipe
#define LIB_fnc_testFunc					jayarma2lib_fnc_testFunc
#define LIB_fnc_stringContains				jayarma2lib_fnc_stringContains
#define LIB_ui_fnc_add						CBA_ui_fnc_add
#define LIB_fnc_setVarNet					CBA_fnc_setVarNet