Hz_econ_cfg_magazineRestrictions_default =
[



"RHS_MAG_M7A3_CS",
"RHS_MAG_AN_M14_TH3",
"ACE_M14",
"RHS_MAG_FAKEL",
"RHS_MAG_FAKELS",
"RHS_MAG_MK84",
"ACE_M84",
"RHS_MAG_MK3A2",
"RHS_MAG_PLAMYAM",
"RHS_MAG_RGN",
"RHS_MAG_RGO",
"RHS_MAG_ZARYA2",


"APERSMINEDISPENSER_MAG",
"IEDLANDBIG_REMOTE_MAG",
"IEDURBANBIG_REMOTE_MAG",
"RHSUSF_M112_MAG",
"DEMOCHARGE_REMOTE_MAG",
"RHSUSF_M112X4_MAG",
"RHSUSF_MINE_M14_MAG",
"ATMINE_RANGE_MAG",
"SATCHELCHARGE_REMOTE_MAG",
"CLAYMOREDIRECTIONALMINE_REMOTE_MAG",
"RHS_MINE_M19_MAG",
"APERSBOUNDINGMINE_RANGE_MAG",
"SLAMDIRECTIONALMINE_WIRE_MAG",
"RHS_MAG_MINE_PFM1",
"RHS_MINE_PMN2_MAG",
"APERSTRIPMINE_WIRE_MAG",
"RHS_MAG_MINE_PTM1",
"IEDLANDSMALL_REMOTE_MAG",
"IEDURBANSMALL_REMOTE_MAG",
"RHS_MINE_TM62M_MAG",
"TRAININGMINE_MAG",
"APERSMINE_RANGE_MAG",
"ACE_FLARETRIPMINE_MAG",
"CUP_MINEE_M",
"CUP_PIPEBOMB_M",
"CUP_PIPEBOMB_M",

"HLC_45RND_762X39_AP_RPK",
"HLC_75RND_762X39_AP_RPK",
"HLC_45RND_762X39_M_RPK",
"HLC_75RND_762X39_M_RPK",
"HLC_45RND_762X39_T_RPK",
"HLC_45RND_545X39_M_RPK",
"HLC_60RND_545X39_T_RPK",
"HLC_45RND_545X39_T_RPK"

];